/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Audio payload used for voice creation.
 */
export type AudioData = {
  /**
   * Required. The raw audio bytes.
   */
  data: string;
  /**
   * Required. The IANA MIME type of the audio data (for example, `audio/wav` or
   *
   * @remarks
   * `audio/mpeg`).
   */
  mime_type: string;
};
