/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { VoiceInput } from "./voice-input.js";

/**
 * Request message for `VoicesService.CreateVoice`.
 */
export type CreateVoiceRequest = {
  /**
   * Optional. Whether the created voice is persisted and managed by Google.
   *
   * @remarks
   *
   * * When `true`, Google stores the voice and returns `Voice.id` (for example,
   *   `voice_abc123def456`), which can be managed via `GetVoice`, `ListVoices`,
   *   and `DeleteVoice` and referenced by ID in synthesis requests. Projects
   *   are subject to a maximum active stored voice quota; exceeding the quota
   *   returns `RESOURCE_EXHAUSTED`.
   * * When `false` (default), the voice is not stored by Google and `Voice.key`
   *   (for example, `voicekey_...`) is returned for client-side storage and
   *   synthesis. Optional discovery metadata fields on `voice` are not
   *   persisted or returned when `store` is `false`.
   * * Required to be `true` when `voice.type` is `"prompted"`
   *   (otherwise fails with `INVALID_ARGUMENT`).
   */
  store?: boolean | undefined;
  /**
   * A voice resource representing either a custom voice (created via
   *
   * @remarks
   * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
   */
  voice: VoiceInput;
};
