/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { VoiceOutput } from "./voice-output.js";

/**
 * Response message for `VoicesService.ListVoices`.
 */
export type ListVoicesResponse = {
  /**
   * A token that can be sent as `page_token` to retrieve the next page.
   *
   * @remarks
   * If empty, there are no subsequent pages.
   */
  next_page_token?: string | undefined;
  /**
   * The voices from the specified collection.
   */
  voices?: Array<VoiceOutput> | undefined;
};
