/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Parameters for prompted voice generation.
 *
 * @remarks
 * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
 * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
 */
export type PromptedVoice = {
  /**
   * Required. The natural-language prompt describing the desired voice, e.g.
   *
   * @remarks
   * "A deep, booming male voice of a massive evil ogre in his middle years."
   */
  input: string;
};
