/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AudioData } from "./audio-data.js";

/**
 * Input only. Parameters for replicated voice generation.
 *
 * @remarks
 * Required on input when `type` is `"replicated"`. Not returned in
 * responses.
 */
export type ReplicatedVoice = {
  /**
   * Audio payload used for voice creation.
   */
  consent_audio: AudioData;
  /**
   * Audio payload used for voice creation.
   */
  source_audio: AudioData;
};
