/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";
import { Pitch } from "./pitch.js";
import { PromptedVoice } from "./prompted-voice.js";
import { VoiceType } from "./voice-type.js";

/**
 * A voice resource representing either a custom voice (created via
 *
 * @remarks
 * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
 */
export type VoiceOutput = {
  /**
   * Optional. Regional accent descriptor (e.g. "American", "British").
   */
  accent?: string | undefined;
  /**
   * Optional. Optimal usage context or domain (e.g. "Conversational",
   *
   * @remarks
   * "Audiobook", "News").
   */
  context?: string | undefined;
  /**
   * Optional. Descriptive summary of vocal timbre, personality, and tone.
   */
  description?: string | undefined;
  /**
   * Optional. User-provided display name for a stored voice (`store = true`),
   *
   * @remarks
   * or the catalog name for a prebuilt voice.
   */
  display_name?: string | undefined;
  /**
   * Output only. The timestamp at which a custom stored voice (`store = true`)
   *
   * @remarks
   * or replicated voice key (`store = false`) expires. Unset for prebuilt
   * catalog voices (`"prebuilt"`), which do not expire.
   */
  expire_time?: string | undefined;
  /**
   * Optional. Perceived voice gender presentation (e.g. "female", "male",
   *
   * @remarks
   * "neutral").
   */
  gender?: string | undefined;
  /**
   * Output only. The unique identifier of the voice.
   *
   * @remarks
   *
   * * For Google-managed custom voices (`store = true`), this is a generated ID
   *   with prefix `voice_` (for example, `voice_abc123def456`). Pass
   *   `voices/{id}` as the `name` in `GetVoice` and `DeleteVoice`, and pass
   *   `{id}` directly to `SpeechConfig.voice_config.voice` (or
   *   `SpeechConfig.voice`) during speech synthesis.
   * * For prebuilt catalog voices (`"prebuilt"` returned by `ListVoices`), this
   *   is the speaker name (for example, `Puck` or `Charon`).
   * * Unset when `CreateVoice` is called with `store = false`.
   */
  id?: string | undefined;
  /**
   * Output only. The client-managed voice replication key (with prefix
   *
   * @remarks
   * `voicekey_`). Returned only by `CreateVoice` when `type` is `"replicated"`
   * and `store` is `false`. Pass this key to `SpeechConfig.voice_config.voice`
   * (or `SpeechConfig.voice`) during speech synthesis.
   */
  key?: string | undefined;
  /**
   * Optional. Primary BCP-47 language tag (e.g. "en-US", "fr-FR").
   */
  language_code?: string | undefined;
  /**
   * Optional. The model used to design or replicate the voice.
   *
   * @remarks
   * If omitted in `CreateVoice`, defaults to the latest supported voice design
   * model. Returned in `CreateVoice`, `GetVoice`, and `ListVoices` responses
   * for custom voices (`"prompted"` and `"replicated"`); unset for `"prebuilt"`
   * voices. Created voices can be synthesized across any supported TTS
   * synthesis model.
   */
  model?: string | undefined;
  /**
   * Optional. Intended persona or character archetype (e.g. "Warm, Friendly",
   *
   * @remarks
   * "Narrator").
   */
  persona?: string | undefined;
  pitch?: Pitch | undefined;
  /**
   * Parameters for prompted voice generation.
   *
   * @remarks
   * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
   * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
   */
  prompted?: PromptedVoice | undefined;
  /**
   * Optional. ISO 3166-1 alpha-2 or UN M.49 geographic region code (e.g. "US",
   *
   * @remarks
   * "GB", "001").
   */
  region_code?: string | undefined;
  type: VoiceType;
  /**
   * Statistics on the interaction request's token usage.
   */
  usage?: interactions.Usage | undefined;
};
