/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Pitch } from "./pitch.js";
import { PromptedVoice } from "./prompted-voice.js";
import { ReplicatedVoice } from "./replicated-voice.js";
import { VoiceType } from "./voice-type.js";

/**
 * A voice resource representing either a custom voice (created via
 *
 * @remarks
 * `CreateVoice`) or a prebuilt system voice (returned by `ListVoices`).
 */
export type VoiceInput = {
  /**
   * Optional. Regional accent descriptor (e.g. "American", "British").
   */
  accent?: string | undefined;
  /**
   * Optional. Optimal usage context or domain (e.g. "Conversational",
   *
   * @remarks
   * "Audiobook", "News").
   */
  context?: string | undefined;
  /**
   * Optional. Descriptive summary of vocal timbre, personality, and tone.
   */
  description?: string | undefined;
  /**
   * Optional. User-provided display name for a stored voice (`store = true`),
   *
   * @remarks
   * or the catalog name for a prebuilt voice.
   */
  display_name?: string | undefined;
  /**
   * Optional. Perceived voice gender presentation (e.g. "female", "male",
   *
   * @remarks
   * "neutral").
   */
  gender?: string | undefined;
  /**
   * Optional. Primary BCP-47 language tag (e.g. "en-US", "fr-FR").
   */
  language_code?: string | undefined;
  /**
   * Optional. The model used to design or replicate the voice.
   *
   * @remarks
   * If omitted in `CreateVoice`, defaults to the latest supported voice design
   * model. Returned in `CreateVoice`, `GetVoice`, and `ListVoices` responses
   * for custom voices (`"prompted"` and `"replicated"`); unset for `"prebuilt"`
   * voices. Created voices can be synthesized across any supported TTS
   * synthesis model.
   */
  model?: string | undefined;
  /**
   * Optional. Intended persona or character archetype (e.g. "Warm, Friendly",
   *
   * @remarks
   * "Narrator").
   */
  persona?: string | undefined;
  pitch?: Pitch | undefined;
  /**
   * Parameters for prompted voice generation.
   *
   * @remarks
   * Required in `CreateVoice` when `type` is `"prompted"`. Returned in
   * `CreateVoice`, `GetVoice`, and `ListVoices` responses for prompted voices.
   */
  prompted?: PromptedVoice | undefined;
  /**
   * Optional. ISO 3166-1 alpha-2 or UN M.49 geographic region code (e.g. "US",
   *
   * @remarks
   * "GB", "001").
   */
  region_code?: string | undefined;
  /**
   * Input only. Parameters for replicated voice generation.
   *
   * @remarks
   * Required on input when `type` is `"replicated"`. Not returned in
   * responses.
   */
  replicated?: ReplicatedVoice | undefined;
  type: VoiceType;
};
