/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EnvironmentVariableConfig } from "./environment-variable-config.js";
import { HttpBearerConfig } from "./http-bearer-config.js";
import { OAuth2Config } from "./o-auth2-config.js";

/**
 * Represents the fields of a Credential provided on creation.
 */
export type CredentialCreateParams =
  | EnvironmentVariableConfig
  | HttpBearerConfig
  | OAuth2Config;
