/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Output only. Current status of the credential.
 */
export type Status = "active" | "revoked" | (string & {});

/**
 * Required. Output only. The type of credential.
 */
export type Type =
  | "bearer_token"
  | "oauth2"
  | "environment_variable"
  | (string & {});

/**
 * Server-managed credential resource stored in Secret Manager.
 */
export type Credential = {
  /**
   * Output only. The timestamp when the credential was created.
   */
  create_time?: string | undefined;
  /**
   * Required. Output only. Identifier. Unique identifier for the credential.
   */
  id: string;
  /**
   * Output only. Current status of the credential.
   */
  status?: Status | undefined;
  /**
   * Required. Output only. The type of credential.
   */
  type?: Type | undefined;
  /**
   * Output only. The timestamp when the credential was last updated.
   */
  update_time?: string | undefined;
};
