/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EnvironmentVariableUpdateConfig } from "./environment-variable-update-config.js";
import { HttpBearerUpdateConfig } from "./http-bearer-update-config.js";
import { OAuth2UpdateConfig } from "./o-auth2-update-config.js";

/**
 * Represents the fields of a Credential that can be updated.
 */
export type CredentialUpdate =
  | EnvironmentVariableUpdateConfig
  | HttpBearerUpdateConfig
  | OAuth2UpdateConfig;
