/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InjectionLocationEnum } from "./injection-location-enum.js";

/**
 * Required. Locations where the environment variable can be injected in
 *
 * @remarks
 * outgoing HTTP requests. Must contain at least one location.
 * Accepts either a single location (e.g. "header") or an array of locations.
 */
export type EnvironmentVariableConfigInjectionLocation =
  | InjectionLocationEnum
  | Array<InjectionLocationEnum>;

/**
 * Configuration for environment variable credentials.
 */
export type EnvironmentVariableConfig = {
  id: string;
  /**
   * Required. Locations where the environment variable can be injected in
   *
   * @remarks
   * outgoing HTTP requests. Must contain at least one location.
   * Accepts either a single location (e.g. "header") or an array of locations.
   */
  injection_location: InjectionLocationEnum | Array<InjectionLocationEnum>;
  /**
   * Optional. List of domains allowed to receive this environment variable
   *
   * @remarks
   * value in HTTP requests.
   */
  trusted_domains?: Array<string> | undefined;
  type: "environment_variable";
  /**
   * Required. Input only. Secret value of the environment variable. Write-only; never
   *
   * @remarks
   * returned in responses.
   */
  value: string;
};
