/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InjectionLocationEnum } from "./injection-location-enum.js";

/**
 * Optional. Locations where the environment variable can be injected in
 *
 * @remarks
 * outgoing HTTP requests.
 * Accepts either a single location (e.g. "header") or an array of locations.
 */
export type EnvironmentVariableUpdateConfigInjectionLocation =
  | InjectionLocationEnum
  | Array<InjectionLocationEnum>;

/**
 * Configuration for updating environment variable credentials.
 */
export type EnvironmentVariableUpdateConfig = {
  /**
   * Optional. Locations where the environment variable can be injected in
   *
   * @remarks
   * outgoing HTTP requests.
   * Accepts either a single location (e.g. "header") or an array of locations.
   */
  injection_location?:
    | InjectionLocationEnum
    | Array<InjectionLocationEnum>
    | undefined;
  /**
   * Optional. List of domains allowed to receive this environment variable
   *
   * @remarks
   * value in HTTP requests.
   */
  trusted_domains?: Array<string> | undefined;
  type: "environment_variable";
  /**
   * Optional. Input only. Secret value of the environment variable. Write-only; never
   *
   * @remarks
   * returned in responses.
   */
  value?: string | undefined;
};
