/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for HTTP Bearer token credentials.
 */
export type HttpBearerConfig = {
  /**
   * Optional. Header name to inject the token into. Defaults to
   *
   * @remarks
   * 'Authorization'.
   */
  header_name?: string | undefined;
  id: string;
  /**
   * Optional. Prefix to prepend to the token. Defaults to 'Bearer'. Set to ''
   *
   * @remarks
   * for no prefix.
   */
  prefix?: string | undefined;
  /**
   * Required. Input only. The static bearer token. Write-only; never returned in responses.
   */
  token: string;
  type: "bearer_token";
};
