/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for OAuth2 credentials with automatic token refresh.
 */
export type OAuth2Config = {
  /**
   * Required. OAuth2 client ID.
   */
  client_id: string;
  /**
   * Required. Input only. OAuth2 client secret. Write-only; never returned in responses.
   */
  client_secret: string;
  id: string;
  /**
   * Required. Input only. OAuth2 refresh token. Write-only; never returned in responses.
   */
  refresh_token: string;
  /**
   * Optional. List of OAuth2 scopes.
   */
  scopes?: Array<string> | undefined;
  /**
   * Required. OAuth2 token endpoint URL for refreshing access tokens.
   */
  token_url: string;
  type: "oauth2";
};
