/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for updating OAuth2 credentials.
 */
export type OAuth2UpdateConfig = {
  /**
   * Optional. OAuth2 client ID.
   */
  client_id?: string | undefined;
  /**
   * Optional. Input only. OAuth2 client secret. Write-only; never returned in responses.
   */
  client_secret?: string | undefined;
  /**
   * Optional. Input only. OAuth2 refresh token. Write-only; never returned in responses.
   */
  refresh_token?: string | undefined;
  /**
   * Optional. List of OAuth2 scopes.
   */
  scopes?: Array<string> | undefined;
  /**
   * Optional. OAuth2 token endpoint URL for refreshing access tokens.
   */
  token_url?: string | undefined;
  type: "oauth2";
};
