/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";
import { GoogleGenAiError } from "./google-gen-ai-error.js";

/**
 * Server Error
 */
export type ListAgentsServerErrorData = {
  /**
   * Error message from an interaction.
   */
  error: interactions.ErrorT;
};

/**
 * Server Error
 */
export class ListAgentsServerError extends GoogleGenAiError {
  /**
   * Error message from an interaction.
   */
  error: interactions.ErrorT;

  /** The original data that was passed to this error instance. */
  data$: ListAgentsServerErrorData;

  constructor(
    err: ListAgentsServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ListAgentsServerError";
  }
}

/**
 * Client Error
 */
export type ListAgentsClientErrorData = {
  /**
   * Error message from an interaction.
   */
  error: interactions.ErrorT;
};

/**
 * Client Error
 */
export class ListAgentsClientError extends GoogleGenAiError {
  /**
   * Error message from an interaction.
   */
  error: interactions.ErrorT;

  /** The original data that was passed to this error instance. */
  data$: ListAgentsClientErrorData;

  constructor(
    err: ListAgentsClientErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ListAgentsClientError";
  }
}
