/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { credentialsCreate } from "../funcs/credentials-create.js";
import { credentialsDelete } from "../funcs/credentials-delete.js";
import { credentialsGet } from "../funcs/credentials-get.js";
import { credentialsList } from "../funcs/credentials-list.js";
import { credentialsUpdate } from "../funcs/credentials-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as credentials from "../models/credentials/index.js";
import * as interactions from "../models/interactions/index.js";
import {
  CreateCredentialParams,
  DeleteCredentialParams,
  GetCredentialParams,
  ListCredentialsParams,
  UpdateCredentialParams,
} from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Credentials extends ClientSDK {
  /**
   * Lists credentials for a project.
   */
  list(
    params?: ListCredentialsParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<credentials.CredentialListResponse> {
    return unwrapAsAPIPromise(credentialsList(
      this,
      params?.api_version,
      params?.page_size,
      params?.page_token,
      options,
    ));
  }

  /**
   * Creates a credential.
   */
  create(
    params: CreateCredentialParams,
    options?: RequestOptions,
  ): APIPromise<credentials.Credential> {
    const { api_version, ...body } = params;
    return unwrapAsAPIPromise(credentialsCreate(
      this,
      body,
      api_version,
      options,
    ));
  }

  /**
   * Deletes a credential. Fails if referenced by active triggers.
   */
  delete(
    id: string,
    params?: DeleteCredentialParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.Empty> {
    return unwrapAsAPIPromise(credentialsDelete(
      this,
      id,
      params?.api_version,
      options,
    ));
  }

  /**
   * Gets metadata of a single credential (no secret fields).
   */
  get(
    id: string,
    params?: GetCredentialParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<credentials.Credential> {
    return unwrapAsAPIPromise(credentialsGet(
      this,
      id,
      params?.api_version,
      options,
    ));
  }

  /**
   * Updates a credential.
   */
  update(
    id: string,
    params: UpdateCredentialParams,
    options?: RequestOptions,
  ): APIPromise<credentials.Credential> {
    const { api_version, update_mask, ...body } = params;
    return unwrapAsAPIPromise(credentialsUpdate(
      this,
      id,
      body,
      api_version,
      update_mask,
      options,
    ));
  }
}
