/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsCreateEnvironment } from "../funcs/environments-create-environment.js";
import { environmentsDeleteEnvironment } from "../funcs/environments-delete-environment.js";
import { environmentsGetEnvironment } from "../funcs/environments-get-environment.js";
import { environmentsListEnvironments } from "../funcs/environments-list-environments.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as environments from "../models/environments/index.js";
import * as interactions from "../models/interactions/index.js";
import {
  CreateEnvironmentParams,
  ListEnvironmentsParams,
} from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Environments extends ClientSDK {
  /**
   * Lists environments (HTTP endpoint).
   */
  listEnvironments(
    params?: ListEnvironmentsParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<environments.ListEnvironmentsResponse> {
    return unwrapAsAPIPromise(environmentsListEnvironments(
      this,
      params?.page_size,
      params?.page_token,
      options,
    ));
  }

  /**
   * Creates an environment (HTTP endpoint).
   */
  createEnvironment(
    params: CreateEnvironmentParams,
    options?: RequestOptions,
  ): APIPromise<environments.Environment> {
    return unwrapAsAPIPromise(environmentsCreateEnvironment(
      this,
      params,
      options,
    ));
  }

  /**
   * Gets an environment (HTTP endpoint).
   */
  getEnvironment(
    id: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<environments.Environment> {
    return unwrapAsAPIPromise(environmentsGetEnvironment(
      this,
      id,
      options,
    ));
  }

  /**
   * Deletes an environment (HTTP endpoint).
   */
  deleteEnvironment(
    id: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.Empty> {
    return unwrapAsAPIPromise(environmentsDeleteEnvironment(
      this,
      id,
      options,
    ));
  }
}
