/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsCreateEnvironment } from "../funcs/environments-create-environment.js";
import { environmentsDeleteEnvironment } from "../funcs/environments-delete-environment.js";
import { environmentsGetEnvironmentFiles } from "../funcs/environments-get-environment-files.js";
import { environmentsGetEnvironment } from "../funcs/environments-get-environment.js";
import { environmentsListEnvironments } from "../funcs/environments-list-environments.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as interactions from "../models/interactions/index.js";
import {
  EnvironmentParams,
  GetEnvironmentFilesParams,
  ListEnvironmentsParams,
} from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Environments extends ClientSDK {
  /**
   * Creates an environment.
   */
  createEnvironment(
    params?: EnvironmentParams,
    options?: RequestOptions,
  ): APIPromise<interactions.Environment> {
    return unwrapAsAPIPromise(environmentsCreateEnvironment(
      this,
      params,
      options,
    ));
  }

  /**
   * Lists environments.
   */
  listEnvironments(
    params?: ListEnvironmentsParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.ListEnvironmentsResponse> {
    return unwrapAsAPIPromise(environmentsListEnvironments(
      this,
      params?.page_size,
      params?.page_token,
      options,
    ));
  }

  /**
   * Gets an environment.
   */
  getEnvironment(
    environment: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.Environment> {
    return unwrapAsAPIPromise(environmentsGetEnvironment(
      this,
      environment,
      options,
    ));
  }

  /**
   * Deletes an environment.
   */
  deleteEnvironment(
    environment: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.Empty> {
    return unwrapAsAPIPromise(environmentsDeleteEnvironment(
      this,
      environment,
      options,
    ));
  }

  /**
   * Retrieves a file or directory from an environment's snapshot.
   *
   * If the path points to a directory:
   *   - If `alt=media` is specified, it downloads the directory as a tarball.
   *   - Otherwise, it returns the metadata of the files and directories
   *     immediately within it (directory listing).
   * If the path points to a file:
   *   - If `alt=media` is specified, it downloads the file.
   *   - Otherwise, it returns the file metadata.
   */
  getEnvironmentFiles(
    environment: string,
    path: string,
    params?: GetEnvironmentFilesParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.GetEnvironmentFilesResponse> {
    return unwrapAsAPIPromise(environmentsGetEnvironmentFiles(
      this,
      environment,
      path,
      params?.page_size,
      params?.page_token,
      params?.recursive,
      options,
    ));
  }
}
