/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsFilesList } from "../funcs/environments-files-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as environments from "../models/environments/index.js";
import { GetEnvironmentFilesParams } from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Files extends ClientSDK {
  /**
   * Retrieves a file or directory from an environment's snapshot.
   */
  list(
    environment: string,
    path: string,
    params?: GetEnvironmentFilesParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<environments.GetEnvironmentFilesResponse> {
    return unwrapAsAPIPromise(environmentsFilesList(
      this,
      environment,
      path,
      params?.api_version,
      params?.page_size,
      params?.page_token,
      params?.recursive,
      options,
    ));
  }
}
