/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { environmentsInternalStartUpload } from "../funcs/environments-internal-start-upload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { StartEnvironmentFileUploadParams } from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Internal extends ClientSDK {
  /**
   * Start an environment file upload
   *
   * @remarks
   * Starts a resumable upload session for a file in an environment workspace.
   * Upload the file bytes to the URL returned in the `X-Goog-Upload-URL`
   * response header, using the resumable upload protocol.
   */
  startUpload(
    environment: string,
    path: string,
    params: StartEnvironmentFileUploadParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<operations.StartEnvironmentFileUploadResponse | undefined> {
    return unwrapAsAPIPromise(environmentsInternalStartUpload(
      this,
      environment,
      path,
      params["X-Goog-Upload-Command"],
      params["X-Goog-Upload-Header-Content-Length"],
      params["X-Goog-Upload-Header-Content-Type"],
      params["X-Goog-Upload-Protocol"],
      params.api_version,
      params.extract,
      params.overwrite,
      options,
    ));
  }
}
