/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { interactionsCancel } from "../funcs/interactions-cancel.js";
import { interactionsCreate } from "../funcs/interactions-create.js";
import { interactionsDelete } from "../funcs/interactions-delete.js";
import { interactionsGet } from "../funcs/interactions-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as interactions from "../models/interactions/index.js";
import * as operations from "../models/operations/index.js";
import {
  GetInteractionByIdParams,
  GetInteractionByIdParamsNonStreaming,
  GetInteractionByIdParamsStreaming,
} from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Interactions extends ClientSDK {
  /**
   * Generates a set of responses from the model.
   */
  create(
    request: interactions.CreateInteractionRequest & {
      stream?: false | undefined;
    },
    options?: RequestOptions,
  ): APIPromise<operations.CreateInteractionResponse>;
  create(
    request: interactions.CreateInteractionRequest & { stream: true },
    options?: RequestOptions,
  ): APIPromise<operations.CreateInteractionResponse>;
  create(
    request: interactions.CreateInteractionRequest,
    options?: RequestOptions,
  ): APIPromise<operations.CreateInteractionResponse>;
  create(
    request: interactions.CreateInteractionRequest,
    options?: RequestOptions,
  ): APIPromise<operations.CreateInteractionResponse> {
    return unwrapAsAPIPromise(interactionsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Gets an interaction.
   */
  get(
    id: string,
    params?: GetInteractionByIdParamsNonStreaming,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<operations.GetInteractionByIdResponse>;
  get(
    id: string,
    params: GetInteractionByIdParamsStreaming,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<operations.GetInteractionByIdResponse>;
  get(
    id: string,
    params?: GetInteractionByIdParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<operations.GetInteractionByIdResponse>;
  get(
    id: string,
    params?: GetInteractionByIdParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<operations.GetInteractionByIdResponse> {
    return unwrapAsAPIPromise(interactionsGet(
      this,
      id,
      params?.include_input,
      params?.last_event_id,
      params?.stream,
      options,
    ));
  }

  /**
   * Deletes an interaction.
   */
  delete(
    id: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<void> {
    return unwrapAsAPIPromise(interactionsDelete(
      this,
      id,
      options,
    ));
  }

  /**
   * Cancels an interaction.
   */
  cancel(
    id: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.Interaction> {
    return unwrapAsAPIPromise(interactionsCancel(
      this,
      id,
      options,
    ));
  }
}
