/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { LocationsAgents } from "./locations-agents.js";

export class Locations extends ClientSDK {
  private _agents?: LocationsAgents;
  get agents(): LocationsAgents {
    return (this._agents ??= new LocationsAgents(this._options));
  }
}
