/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsLocationsAgentsUpdateAgentByProjectsIdAndLocationsIdAndAgentsId } from "../funcs/projects-locations-agents-update-agent-by-projects-id-and-locations-id-and-agents-id.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as agents from "../models/agents/index.js";
import { UpdateAgentByProjectsIdAndLocationsIdAndAgentsIdParams } from "../models/operations/method-params.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class LocationsAgents extends ClientSDK {
  /**
   * Updates an existing Agent.
   */
  updateAgentByProjectsIdAndLocationsIdAndAgentsId(
    agents_id: string,
    locations_id: string,
    projects_id: string,
    params?: UpdateAgentByProjectsIdAndLocationsIdAndAgentsIdParams,
    options?: RequestOptions,
  ): APIPromise<agents.Agent> {
    const { api_version, update_mask, ...body$body } = params ?? {};
    const body = params === undefined || Object.keys(body$body).length === 0
      ? undefined
      : body$body;
    return unwrapAsAPIPromise(
      projectsLocationsAgentsUpdateAgentByProjectsIdAndLocationsIdAndAgentsId(
        this,
        agents_id,
        locations_id,
        projects_id,
        api_version,
        update_mask,
        body,
        options,
      ),
    );
  }
}
