/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Locations } from "./locations.js";

export class Projects extends ClientSDK {
  private _locations?: Locations;
  get locations(): Locations {
    return (this._locations ??= new Locations(this._options));
  }
}
