/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { voicesCreate } from "../funcs/voices-create.js";
import { voicesDelete } from "../funcs/voices-delete.js";
import { voicesGet } from "../funcs/voices-get.js";
import { voicesList } from "../funcs/voices-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import {
  DeleteVoiceParams,
  GetVoiceParams,
  ListVoicesParams,
} from "../models/operations/method-params.js";
import * as voices from "../models/voices/index.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Voices extends ClientSDK {
  /**
   * Lists custom stored voices owned by the caller (ordered newest first)
   * followed by prebuilt system voices from Google's voice catalog.
   */
  list(
    params?: ListVoicesParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<voices.ListVoicesResponse> {
    return unwrapAsAPIPromise(voicesList(
      this,
      params?.api_version,
      params?.accent,
      params?.contexts,
      params?.gender,
      params?.language_code,
      params?.page_size,
      params?.page_token,
      params?.persona,
      params?.pitch,
      params?.region_code,
      params?.search,
      params?.type,
      options,
    ));
  }

  /**
   * Creates a custom voice from a natural-language prompt
   * (`VOICE_TYPE_PROMPTED`) or from reference and consent audio recordings
   * (`VOICE_TYPE_REPLICATED`).
   */
  create(
    body: voices.CreateVoiceRequest,
    api_version?: string | undefined,
    options?: RequestOptions,
  ): APIPromise<voices.VoiceOutput> {
    return unwrapAsAPIPromise(voicesCreate(
      this,
      body,
      api_version,
      options,
    ));
  }

  /**
   * Deletes a custom stored voice (`store = true`) by resource name.
   * Prebuilt catalog voices (`VOICE_TYPE_PREBUILT`) cannot be deleted.
   */
  delete(
    id: string,
    params?: DeleteVoiceParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<voices.DeleteVoiceResponse> {
    return unwrapAsAPIPromise(voicesDelete(
      this,
      id,
      params?.api_version,
      options,
    ));
  }

  /**
   * Gets a custom stored voice (`store = true`) by resource name.
   * Prebuilt catalog voices (`VOICE_TYPE_PREBUILT`) cannot be retrieved via
   * `GetVoice`; use `ListVoices` instead.
   */
  get(
    id: string,
    params?: GetVoiceParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<voices.VoiceOutput> {
    return unwrapAsAPIPromise(voicesGet(
      this,
      id,
      params?.api_version,
      options,
    ));
  }
}
