/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreate } from "../funcs/webhooks-create.js";
import { webhooksDelete } from "../funcs/webhooks-delete.js";
import { webhooksGet } from "../funcs/webhooks-get.js";
import { webhooksList } from "../funcs/webhooks-list.js";
import { webhooksPing } from "../funcs/webhooks-ping.js";
import { webhooksRotateSigningSecret } from "../funcs/webhooks-rotate-signing-secret.js";
import { webhooksUpdate } from "../funcs/webhooks-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as interactions from "../models/interactions/index.js";
import {
  ListWebhooksParams,
  UpdateWebhookParams,
  WebhookInputParams,
} from "../models/operations/method-params.js";
import * as webhooks from "../models/webhooks/index.js";
import { APIPromise, unwrapAsAPIPromise } from "../types/async.js";

export class Webhooks extends ClientSDK {
  /**
   * Lists all Webhooks.
   */
  list(
    params?: ListWebhooksParams,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<webhooks.WebhookListResponse> {
    return unwrapAsAPIPromise(webhooksList(
      this,
      params?.page_size,
      params?.page_token,
      options,
    ));
  }

  /**
   * Creates a new Webhook.
   */
  create(
    params: WebhookInputParams,
    options?: RequestOptions,
  ): APIPromise<webhooks.Webhook> {
    return unwrapAsAPIPromise(webhooksCreate(
      this,
      params,
      options,
    ));
  }

  /**
   * Gets a specific Webhook.
   */
  get(
    id: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<webhooks.Webhook> {
    return unwrapAsAPIPromise(webhooksGet(
      this,
      id,
      options,
    ));
  }

  /**
   * Deletes a Webhook.
   */
  delete(
    id: string,
    options?: Omit<RequestOptions, "extra_body">,
  ): APIPromise<interactions.Empty> {
    return unwrapAsAPIPromise(webhooksDelete(
      this,
      id,
      options,
    ));
  }

  /**
   * Updates an existing Webhook.
   */
  update(
    id: string,
    params?: UpdateWebhookParams,
    options?: RequestOptions,
  ): APIPromise<webhooks.Webhook> {
    const { update_mask, ...body$body } = params ?? {};
    const body = params === undefined || Object.keys(body$body).length === 0
      ? undefined
      : body$body;
    return unwrapAsAPIPromise(webhooksUpdate(
      this,
      id,
      update_mask,
      body,
      options,
    ));
  }

  /**
   * Sends a ping event to a Webhook.
   */
  ping(
    id: string,
    body?: webhooks.PingWebhookRequest | undefined,
    options?: RequestOptions,
  ): APIPromise<webhooks.WebhookPingResponse> {
    return unwrapAsAPIPromise(webhooksPing(
      this,
      id,
      body,
      options,
    ));
  }

  /**
   * Generates a new signing secret for a Webhook.
   */
  rotateSigningSecret(
    id: string,
    body?: webhooks.RotateSigningSecretRequest | undefined,
    options?: RequestOptions,
  ): APIPromise<webhooks.WebhookRotateSigningSecretResponse> {
    return unwrapAsAPIPromise(webhooksRotateSigningSecret(
      this,
      id,
      body,
      options,
    ));
  }
}
