/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as triggers from "../triggers/index.js";

export type CreateTriggerGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type CreateTriggerRequest = {
  /**
   * Required. The parent resource where this trigger will be created.
   *
   * @remarks
   * Format: `projects/{project}/locations/{location}`
   *
   * Supported only by the Vertex API only.
   */
  parent?: string | undefined;
  /**
   * Required. The trigger configuration to create.
   */
  body: triggers.TriggerCreateParams;
};
