/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as environments from "../environments/index.js";

export type CreateEnvironmentGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type CreateEnvironmentRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * Required. The environment to create.
   */
  body: environments.EnvironmentInput;
};
