/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as credentials from "../credentials/index.js";

export type CreateCredentialGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type CreateCredentialRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Required. The request body.
   */
  body: credentials.CredentialCreateParams;
};
