/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as agents from "../agents/index.js";

export type CreateAgentGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type CreateAgentRequest = {
  parent?: string | undefined;
  body: agents.Agent;
};
