/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as environments from "../environments/index.js";

export type CreateEnvironmentGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type CreateEnvironmentRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Required. The environment to create (HTTP request body).
   */
  body: environments.CreateEnvironmentRequest;
};
