/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as triggers from "../triggers/index.js";

export type CreateTriggerGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type CreateTriggerRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  body: triggers.TriggerInput;
};
