/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Stream } from "../../lib/event-streams.js";
import * as interactions from "../interactions/index.js";

export type CreateInteractionGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

/**
 * The request body.
 */
export type CreateInteractionRequestBody =
  | interactions.CreateAgentInteraction
  | interactions.CreateModelInteraction;

export type CreateInteractionRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * The request body.
   */
  body:
    | interactions.CreateAgentInteraction
    | interactions.CreateModelInteraction;
};

export type CreateInteractionResponse =
  | interactions.Interaction
  | Stream<interactions.InteractionSSEEvent>;
