/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as voices from "../voices/index.js";

export type CreateVoiceGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type CreateVoiceRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * The request body.
   */
  body: voices.CreateVoiceRequest;
};
