/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Stream } from "../../lib/event-streams.js";
import * as interactions from "../interactions/index.js";

export type GetInteractionByIdGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type GetInteractionByIdRequest = {
  /**
   * If true, includes the input in the response.
   */
  include_input?: boolean | undefined;
  /**
   * Part of `name`. Required. The name of the interaction to retrieve.
   *
   * @remarks
   * Format: interactions/{interaction}
   */
  id: string;
  /**
   * If set, resumes the interaction stream from the chunk after the event
   *
   * @remarks
   * marked by the event id. Can only be used if `stream` is true.
   */
  last_event_id?: string | undefined;
  /**
   * If true, streams the interaction events as Server-Sent Events.
   */
  stream?: boolean | undefined;
};

export type GetInteractionByIdResponse =
  | interactions.Interaction
  | Stream<interactions.InteractionSSEEvent>;
