/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type GetTriggerGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type GetTriggerRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Required. The ID of the trigger to retrieve.
   */
  id: string;
};
