/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type GetEnvironmentFilesRequest = {
  /**
   * Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
   */
  environment: string;
  /**
   * Optional. Maximum number of entries to return per page (for directory
   *
   * @remarks
   * listing). If unspecified, defaults to 100. Maximum is 1000.
   */
  page_size?: number | undefined;
  /**
   * Optional. Pagination token for directory listing.
   */
  page_token?: string | undefined;
  /**
   * Resource ID segment making up resource `name`. It identifies the resource within its parent collection as described in https://google.aip.dev/122.
   */
  path: string;
  /**
   * Optional. If true and the path is a directory, recursively lists all files
   *
   * @remarks
   * and subdirectories. Defaults to false (immediate children only).
   */
  recursive?: boolean | undefined;
};
