/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type GetAgentGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type GetAgentRequest = {
  /**
   * Part of `name`.
   */
  id: string;
};
