/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

export type ListInteractionsGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type ListInteractionsRequest = {
  /**
   * Optional. The maximum number of `Interactions` to return (per page).
   */
  page_size?: number | undefined;
  /**
   * Optional. A page token, received from a previous `ListInteractions` call.
   */
  page_token?: string | undefined;
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

/**
 * Error listing interactions
 */
export type ListInteractionsResponseBody = {
  /**
   * Error message from an interaction.
   */
  error?: interactions.ErrorT | undefined;
};

export type ListInteractionsResponse =
  | interactions.ListInteractionsResponse
  | ListInteractionsResponseBody;
