/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListTriggersGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type ListTriggersRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Optional. Filter expression (e.g. `agent="agents/my-agent-id"`). Only
   *
   * @remarks
   * equality filtering on the `agent` field is currently supported.
   */
  filter?: string | undefined;
  /**
   * The maximum number of triggers to return per page.
   */
  page_size?: number | undefined;
  /**
   * A page token from a previous ListTriggers call.
   */
  page_token?: string | undefined;
};
