/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListEnvironmentsGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type ListEnvironmentsRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Optional. Maximum number of environments to return.
   *
   * @remarks
   * If unspecified, defaults to 50. Maximum is 1000.
   */
  page_size?: number | undefined;
  /**
   * Optional. Pagination token.
   */
  page_token?: string | undefined;
};
