/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListAgentsGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type ListAgentsRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  page_size?: number | undefined;
  page_token?: string | undefined;
  /**
   * Required. The parent resource to list agents from.
   *
   * @remarks
   * Format: `projects/{project}/locations/{location}`
   */
  parent?: string | undefined;
};
