/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListVoicesGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type ListVoicesRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Optional. Filter by accent description (e.g. "American", "British").
   *
   * @remarks
   * Case-insensitive exact match. If multiple values are specified, matches
   * voices with any of the specified accents (OR).
   */
  accent?: Array<string> | undefined;
  /**
   * Optional. Filter by intended context or domain (e.g. "News, Commercial").
   *
   * @remarks
   * Case-insensitive exact match. If multiple values are specified, matches
   * voices with any of the specified contexts (OR).
   */
  contexts?: Array<string> | undefined;
  /**
   * Optional. Filter by gender presentation (e.g. "female", "male", "neutral").
   *
   * @remarks
   * Case-insensitive exact match. If multiple values are specified, matches
   * voices with any of the specified genders (OR).
   */
  gender?: Array<string> | undefined;
  /**
   * Optional. Filter by BCP-47 language code (e.g. "en-US").
   *
   * @remarks
   * Case-insensitive exact match. If multiple values are specified, matches
   * voices with any of the specified language codes (OR).
   */
  language_code?: Array<string> | undefined;
  /**
   * Optional. The maximum number of voices to return per page. The service may
   *
   * @remarks
   * return fewer than this value. If unspecified, at most 50 voices are
   * returned. The maximum value is 1000; values above 1000 are coerced to
   * 1000.
   */
  page_size?: number | undefined;
  /**
   * Optional. A page token received from a previous `ListVoices` call. Provide
   *
   * @remarks
   * this to retrieve the subsequent page.
   *
   * When paginating, all filter query parameters (`language_code`,
   * `region_code`, `accent`, `persona`, `context`, `gender`, `pitch`, `type`,
   * and `search`) must match the call that returned this token; otherwise the
   * request fails with `INVALID_ARGUMENT`. `page_size` may change between
   * pages.
   */
  page_token?: string | undefined;
  /**
   * Optional. Filter by vocal persona (e.g. "Warm, Friendly").
   *
   * @remarks
   * Case-insensitive exact match. If multiple values are specified, matches
   * voices with any of the specified personas (OR).
   */
  persona?: Array<string> | undefined;
  /**
   * Optional. Filter by vocal pitch. Accepts `"low"`, `"medium"`, `"high"`
   *
   * @remarks
   * (case-insensitive). If multiple values are specified, matches voices with
   * any of the specified pitches (OR).
   */
  pitch?: Array<string> | undefined;
  /**
   * Optional. Filter by ISO 3166-1 alpha-2 or UN M.49 region code (e.g. "US",
   *
   * @remarks
   * "001").
   * Case-insensitive exact match. If multiple values are specified, matches
   * voices with any of the specified region codes (OR).
   */
  region_code?: Array<string> | undefined;
  /**
   * Optional. Free-text substring search query matched case-insensitively
   *
   * @remarks
   * against both `display_name` and `description`. Maximum 2048 bytes.
   */
  search?: string | undefined;
  /**
   * Optional. Filter by voice type. Accepts `"prebuilt"`, `"replicated"`,
   *
   * @remarks
   * `"prompted"` (case-insensitive). If multiple values are specified, matches
   * voices with any of the specified types (OR).
   */
  type?: Array<string> | undefined;
};
