/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type ListTriggerExecutionsGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type ListTriggerExecutionsRequest = {
  /**
   * Optional. Filter expression.
   */
  filter?: string | undefined;
  /**
   * The maximum number of executions to return per page.
   */
  page_size?: number | undefined;
  /**
   * A page token from a previous ListTriggerExecutions call.
   */
  page_token?: string | undefined;
  /**
   * Required. The trigger ID to list executions from.
   */
  trigger_id: string;
};
