/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type { CreateEnvironmentRequest } from "../environments/create-environment-request.js";
import type { WebhookInput } from "../webhooks/webhook.js";
import type { CreateAgentRequest } from "./create-agent.js";
import type { CreateTriggerRequest } from "./create-trigger.js";
import type { GetInteractionByIdRequest } from "./get-interaction-by-id.js";
import type { ListAgentsRequest } from "./list-agents.js";
import type { ListEnvironmentsRequest } from "./list-environments.js";
import type { ListTriggerExecutionsRequest } from "./list-trigger-executions.js";
import type { ListTriggersRequest } from "./list-triggers.js";
import type { ListWebhooksRequest } from "./list-webhooks.js";
import type { UpdateTriggerRequest } from "./update-trigger.js";
import type { UpdateWebhookRequest } from "./update-webhook.js";

export type CreateAgentParams =
  & Omit<
    CreateAgentRequest,
    "body"
  >
  & CreateAgentRequest["body"];

export type CreateEnvironmentParams = CreateEnvironmentRequest;

export type CreateTriggerParams =
  & Omit<
    CreateTriggerRequest,
    "body"
  >
  & CreateTriggerRequest["body"];

export type GetInteractionByIdParams = Omit<
  GetInteractionByIdRequest,
  "id"
>;

export type GetInteractionByIdParamsNonStreaming = GetInteractionByIdParams & {
  stream?: false | undefined;
};

export type GetInteractionByIdParamsStreaming = GetInteractionByIdParams & {
  stream: true;
};

export type ListAgentsParams = ListAgentsRequest;

export type ListEnvironmentsParams = ListEnvironmentsRequest;

export type ListTriggerExecutionsParams = Omit<
  ListTriggerExecutionsRequest,
  "trigger_id"
>;

export type ListTriggersParams = ListTriggersRequest;

export type ListWebhooksParams = ListWebhooksRequest;

export type UpdateTriggerParams =
  & Omit<
    UpdateTriggerRequest,
    "id" | "body"
  >
  & UpdateTriggerRequest["body"];

export type UpdateWebhookParams =
  & Omit<
    UpdateWebhookRequest,
    "id" | "body"
  >
  & Partial<NonNullable<UpdateWebhookRequest["body"]>>;

export type WebhookInputParams = WebhookInput;
