/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import type { EnvironmentVariableConfig } from "../credentials/environment-variable-config.js";
import type { EnvironmentVariableUpdateConfig } from "../credentials/environment-variable-update-config.js";
import type { HttpBearerConfig } from "../credentials/http-bearer-config.js";
import type { HttpBearerUpdateConfig } from "../credentials/http-bearer-update-config.js";
import type { OAuth2Config } from "../credentials/o-auth2-config.js";
import type { OAuth2UpdateConfig } from "../credentials/o-auth2-update-config.js";
import type { CreateAgentInteraction } from "../interactions/create-agent-interaction.js";
import type { CreateModelInteraction } from "../interactions/create-model-interaction.js";
import type { CancelInteractionByIdRequest } from "./cancel-interaction-by-id.js";
import type { CreateAgentRequest } from "./create-agent.js";
import type { CreateCredentialRequest } from "./create-credential.js";
import type { CreateInteractionRequest } from "./create-interaction.js";
import type { CreateTriggerRequest } from "./create-trigger.js";
import type { CreateWebhookRequest } from "./create-webhook.js";
import type { DeleteAgentRequest } from "./delete-agent.js";
import type { DeleteCredentialRequest } from "./delete-credential.js";
import type { DeleteEnvironmentRequest } from "./delete-environment.js";
import type { DeleteInteractionRequest } from "./delete-interaction.js";
import type { DeleteTriggerRequest } from "./delete-trigger.js";
import type { DeleteWebhookRequest } from "./delete-webhook.js";
import type { GetAgentRequest } from "./get-agent.js";
import type { GetCredentialRequest } from "./get-credential.js";
import type { GetEnvironmentFilesRequest } from "./get-environment-files.js";
import type { GetEnvironmentRequest } from "./get-environment.js";
import type { GetInteractionByIdRequest } from "./get-interaction-by-id.js";
import type { GetTriggerRequest } from "./get-trigger.js";
import type { GetWebhookRequest } from "./get-webhook.js";
import type { ListAgentsRequest } from "./list-agents.js";
import type { ListCredentialsRequest } from "./list-credentials.js";
import type { ListEnvironmentsRequest } from "./list-environments.js";
import type { ListTriggerExecutionsRequest } from "./list-trigger-executions.js";
import type { ListTriggersRequest } from "./list-triggers.js";
import type { ListWebhooksRequest } from "./list-webhooks.js";
import type { RunTriggerRequest } from "./run-trigger.js";
import type { UpdateCredentialRequest } from "./update-credential.js";
import type { UpdateTriggerRequest } from "./update-trigger.js";
import type { UpdateWebhookRequest } from "./update-webhook.js";

export type CancelInteractionByIdParams = Omit<
  CancelInteractionByIdRequest,
  "id"
>;

export type CreateAgentParams =
  & Omit<
    CreateAgentRequest,
    "body"
  >
  & CreateAgentRequest["body"];

export type CreateCredentialParams =
  & Omit<
    CreateCredentialRequest,
    "body"
  >
  & CreateCredentialRequest["body"];

export type EnvironmentVariableConfigParams =
  & Omit<
    CreateCredentialRequest,
    "body"
  >
  & EnvironmentVariableConfig;

export type HttpBearerConfigParams =
  & Omit<
    CreateCredentialRequest,
    "body"
  >
  & HttpBearerConfig;

export type OAuth2ConfigParams =
  & Omit<
    CreateCredentialRequest,
    "body"
  >
  & OAuth2Config;

export type CreateInteractionParams =
  & Omit<
    CreateInteractionRequest,
    "body"
  >
  & CreateInteractionRequest["body"];

export type CreateInteractionParamsNonStreaming = CreateInteractionParams & {
  stream?: false | undefined;
};

export type CreateInteractionParamsStreaming = CreateInteractionParams & {
  stream: true;
};

export type CreateAgentInteractionParams =
  & Omit<
    CreateInteractionRequest,
    "body"
  >
  & CreateAgentInteraction;

export type CreateAgentInteractionParamsNonStreaming =
  & CreateAgentInteractionParams
  & {
    stream?: false | undefined;
  };

export type CreateAgentInteractionParamsStreaming =
  & CreateAgentInteractionParams
  & { stream: true };

export type CreateModelInteractionParams =
  & Omit<
    CreateInteractionRequest,
    "body"
  >
  & CreateModelInteraction;

export type CreateModelInteractionParamsNonStreaming =
  & CreateModelInteractionParams
  & {
    stream?: false | undefined;
  };

export type CreateModelInteractionParamsStreaming =
  & CreateModelInteractionParams
  & { stream: true };

export type CreateTriggerParams =
  & Omit<
    CreateTriggerRequest,
    "body"
  >
  & CreateTriggerRequest["body"];

export type CreateWebhookParams =
  & Omit<
    CreateWebhookRequest,
    "body"
  >
  & CreateWebhookRequest["body"];

export type DeleteAgentParams = Omit<
  DeleteAgentRequest,
  "id"
>;

export type DeleteCredentialParams = Omit<
  DeleteCredentialRequest,
  "id"
>;

export type DeleteEnvironmentParams = Omit<
  DeleteEnvironmentRequest,
  "id"
>;

export type DeleteInteractionParams = Omit<
  DeleteInteractionRequest,
  "id"
>;

export type DeleteTriggerParams = Omit<
  DeleteTriggerRequest,
  "id"
>;

export type DeleteWebhookParams = Omit<
  DeleteWebhookRequest,
  "id"
>;

export type GetAgentParams = Omit<
  GetAgentRequest,
  "id"
>;

export type GetCredentialParams = Omit<
  GetCredentialRequest,
  "id"
>;

export type GetEnvironmentFilesParams = Omit<
  GetEnvironmentFilesRequest,
  "environment" | "path"
>;

export type GetEnvironmentParams = Omit<
  GetEnvironmentRequest,
  "id"
>;

export type GetInteractionByIdParams = Omit<
  GetInteractionByIdRequest,
  "id"
>;

export type GetInteractionByIdParamsNonStreaming = GetInteractionByIdParams & {
  stream?: false | undefined;
};

export type GetInteractionByIdParamsStreaming = GetInteractionByIdParams & {
  stream: true;
};

export type GetTriggerParams = Omit<
  GetTriggerRequest,
  "id"
>;

export type GetWebhookParams = Omit<
  GetWebhookRequest,
  "id"
>;

export type ListAgentsParams = ListAgentsRequest;

export type ListCredentialsParams = ListCredentialsRequest;

export type ListEnvironmentsParams = ListEnvironmentsRequest;

export type ListTriggerExecutionsParams = Omit<
  ListTriggerExecutionsRequest,
  "trigger_id"
>;

export type ListTriggersParams = ListTriggersRequest;

export type ListWebhooksParams = ListWebhooksRequest;

export type RunTriggerParams = Omit<
  RunTriggerRequest,
  "trigger_id"
>;

export type UpdateCredentialParams =
  & Omit<
    UpdateCredentialRequest,
    "id" | "body"
  >
  & UpdateCredentialRequest["body"];

export type EnvironmentVariableUpdateConfigParams =
  & Omit<
    UpdateCredentialRequest,
    "id" | "body"
  >
  & EnvironmentVariableUpdateConfig;

export type HttpBearerUpdateConfigParams =
  & Omit<
    UpdateCredentialRequest,
    "id" | "body"
  >
  & HttpBearerUpdateConfig;

export type OAuth2UpdateConfigParams =
  & Omit<
    UpdateCredentialRequest,
    "id" | "body"
  >
  & OAuth2UpdateConfig;

export type UpdateTriggerParams =
  & Omit<
    UpdateTriggerRequest,
    "id" | "body"
  >
  & UpdateTriggerRequest["body"];

export type UpdateWebhookParams =
  & Omit<
    UpdateWebhookRequest,
    "id" | "body"
  >
  & Partial<NonNullable<UpdateWebhookRequest["body"]>>;
