/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as webhooks from "../webhooks/index.js";

export type RotateSigningSecretGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type RotateSigningSecretRequest = {
  /**
   * Required. The ID of the webhook for which to rotate the signing secret.
   */
  id: string;
  /**
   * Required. The HTTP body of the payload mapping to `revocation_behavior`.
   */
  body?: webhooks.RotateSigningSecretRequest | undefined;
};
