/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type StartEnvironmentFileUploadGlobals = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
};

export type StartEnvironmentFileUploadRequest = {
  /**
   * Which version of the API to use.
   */
  api_version?: string | undefined;
  /**
   * The ID of the environment that owns the destination file.
   */
  environment: string;
  /**
   * The relative destination path inside the environment workspace.
   */
  path: string;
  /**
   * Optional. If true, treats the uploaded file as a tar/tar.gz archive and unpacks it into `path`.
   */
  extract?: boolean | undefined;
  /**
   * Optional. Whether to overwrite the destination file if it already exists.
   */
  overwrite?: boolean | undefined;
  /**
   * Command that starts the resumable upload session.
   */
  "X-Goog-Upload-Command"?: "start" | undefined;
  /**
   * Total number of file bytes that will be uploaded to the session URL.
   */
  "X-Goog-Upload-Header-Content-Length": number;
  /**
   * MIME type of the file that will be uploaded to the session URL.
   */
  "X-Goog-Upload-Header-Content-Type": string;
  /**
   * Resumable upload protocol selector.
   */
  "X-Goog-Upload-Protocol"?: "resumable" | undefined;
};

export type StartEnvironmentFileUploadResponse = {
  Headers: { [k: string]: Array<string> };
};
