/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as agents from "../agents/index.js";

export type UpdateAgentGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type UpdateAgentRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Required. The name of the agent to update. or
   *
   * @remarks
   * `agents/{agent}`
   */
  agentsId: string;
  /**
   * Optional. The list of fields to update.
   */
  update_mask?: string | undefined;
  /**
   * Required. The request body.
   */
  body?: agents.Agent | undefined;
};
