/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as webhooks from "../webhooks/index.js";

export type UpdateWebhookGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type UpdateWebhookRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Required. The ID of the webhook to update.
   */
  id: string;
  /**
   * Optional list of fields to update.
   */
  update_mask?: string | undefined;
  /**
   * Required. The HTTP body of the payload.
   */
  body?: webhooks.WebhookUpdate | undefined;
};
