/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as triggers from "../triggers/index.js";

export type UpdateTriggerGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type UpdateTriggerRequest = {
  /**
   * Required. The ID of the trigger to update.
   */
  id: string;
  /**
   * Required. The trigger with updated fields.
   */
  body: triggers.TriggerUpdate;
};
