/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as credentials from "../credentials/index.js";

export type UpdateCredentialGlobals = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
};

export type UpdateCredentialRequest = {
  /**
   * API version for request routing.
   */
  api_version?: string | undefined;
  /**
   * Required. Resource ID segment making up resource `name`. It identifies the resource
   *
   * @remarks
   * within its parent collection as described in https://google.aip.dev/122.
   */
  id: string;
  /**
   * Optional. The list of fields to update.
   */
  update_mask?: string | undefined;
  /**
   * Required. The request body.
   */
  body: credentials.CredentialUpdate;
};
