/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Trigger } from "./trigger.js";

/**
 * Response message for TriggerService.ListTriggers.
 */
export type ListTriggersResponse = {
  /**
   * A page token, received from a previous `ListTriggers` call.
   *
   * @remarks
   * Provide this to retrieve the subsequent page.
   */
  next_page_token?: string | undefined;
  /**
   * The list of triggers.
   */
  triggers?: Array<Trigger> | undefined;
};
