/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

/**
 * Output only. The current status of the trigger.
 */
export type TriggerStatus = "active" | "paused" | "error" | (string & {});

/**
 * A trigger configuration that is scheduled to run an agent.
 */
export type Trigger = {
  /**
   * The agent that owns this trigger. Set automatically when creating
   *
   * @remarks
   * via the agent-scoped endpoint.
   */
  agent_id?: string | undefined;
  /**
   * Output only. The number of consecutive failures that have occurred
   *
   * @remarks
   * since the last successful execution.
   */
  consecutive_failure_count?: number | undefined;
  /**
   * Output only. The time when the trigger was created.
   */
  create_time?: string | undefined;
  /**
   * Cron-specific trigger configuration.
   */
  cron?: interactions.CronConfig | undefined;
  /**
   * Optional. The display name of the trigger.
   */
  display_name?: string | undefined;
  /**
   * Optional. The environment ID for the trigger execution.
   */
  environment_id?: string | undefined;
  /**
   * Optional. The execution timeout for the triggered interaction.
   */
  execution_timeout_seconds?: number | undefined;
  /**
   * Required. Output only. Identifier. The ID of the trigger.
   */
  id: string;
  /**
   * The Interaction resource.
   */
  interaction?: interactions.Interaction | undefined;
  /**
   * The Interaction resource.
   */
  interaction_template?: interactions.Interaction | undefined;
  /**
   * Output only. The time when the trigger was last paused.
   */
  last_pause_time?: string | undefined;
  /**
   * Output only. The time when the trigger was last resumed.
   */
  last_resume_time?: string | undefined;
  /**
   * Output only. The time when the trigger was last run.
   */
  last_run_time?: string | undefined;
  /**
   * Optional. The maximum number of consecutive failures allowed before
   *
   * @remarks
   * the trigger is automatically paused (status becomes ERROR).
   */
  max_consecutive_failures?: number | undefined;
  /**
   * Output only. The time when the trigger is scheduled to run next.
   */
  next_run_time?: string | undefined;
  /**
   * Output only. The ID of the last interaction created by this trigger.
   */
  previous_interaction_id?: string | undefined;
  /**
   * Deprecated: Use cron.schedule instead.
   *
   * @remarks
   * The cron schedule on which the trigger should run.
   * Standard cron format.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  schedule?: string | undefined;
  /**
   * Execute a script inside the agent's container environment.
   */
  script?: interactions.Script | undefined;
  /**
   * Output only. The current status of the trigger.
   */
  status?: TriggerStatus | undefined;
  /**
   * Deprecated: Use cron.time_zone instead.
   *
   * @remarks
   * Time zone in which the schedule should be interpreted.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  time_zone?: string | undefined;
  /**
   * Output only. The time when the trigger was last updated.
   */
  update_time?: string | undefined;
  /**
   * Webhook-specific trigger configuration.
   */
  webhook?: interactions.WebhookTriggerConfig | undefined;
};
