/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { TriggerInteractionRequest } from "./trigger-interaction-request.js";

/**
 * A trigger configuration that is scheduled to run an agent.
 */
export type TriggerInput = {
  /**
   * Optional. The display name of the trigger.
   */
  display_name?: string | undefined;
  /**
   * Optional. The environment ID for the trigger execution.
   */
  environment_id?: string | undefined;
  /**
   * Optional. The execution timeout for the triggered interaction.
   */
  execution_timeout_seconds?: number | undefined;
  /**
   * Configuration parameters for the interaction request template.
   */
  interaction: TriggerInteractionRequest;
  /**
   * Optional. The maximum number of consecutive failures allowed before
   *
   * @remarks
   * the trigger is automatically paused (status becomes ERROR).
   */
  max_consecutive_failures?: number | undefined;
  /**
   * Required. The cron schedule on which the trigger should run.
   *
   * @remarks
   * Standard cron format.
   */
  schedule: string;
  /**
   * Required. Time zone in which the schedule should be interpreted.
   */
  time_zone: string;
};
