/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

/**
 * Configuration parameters for the interaction request template.
 */
export type TriggerInteractionRequest = {
  /**
   * Input only. Whether the interaction will be streamed.
   */
  stream?: boolean | undefined;
  /**
   * Input only. Whether to store the response and request for later retrieval.
   */
  store?: boolean | undefined;
  /**
   * Input only. Whether to run the model interaction in the background.
   */
  background?: boolean | undefined;
  /**
   * The input for the interaction.
   */
  input?: interactions.InteractionsInput | undefined;
  /**
   * The agent to execute.
   */
  agent?: string | undefined;
  /**
   * The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
   */
  model?: interactions.Model | undefined;
  /**
   * Configuration for dynamic agents.
   */
  dynamic_config?: interactions.DynamicAgentConfig | undefined;
  /**
   * Configuration for the Deep Research agent.
   */
  deep_research_config?: interactions.DeepResearchAgentConfig | undefined;
  /**
   * Labels for the interaction.
   */
  labels?: { [k: string]: string } | undefined;
  /**
   * A list of tool declarations the model may call during interaction.
   */
  tools?: Array<interactions.Tool> | undefined;
  /**
   * System instruction for the interaction.
   */
  system_instruction?: string | undefined;
  /**
   * Configuration parameters for model interactions.
   */
  generation_config?: interactions.GenerationConfig | undefined;
  /**
   * The requested modalities of the response.
   */
  response_modalities?: Array<interactions.ResponseModality> | undefined;
  /**
   * The mime type of the response.
   */
  response_mime_type?: string | undefined;
  /**
   * Optional. The ID of the previous interaction, if any.
   */
  previous_interaction_id?: string | undefined;
  service_tier?: interactions.ServiceTier | undefined;
  /**
   * Message for configuring webhook events for a request.
   */
  webhook_config?: interactions.WebhookConfig | undefined;
};
