/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FindRequest } from "./find-request.js";
import { FixRequest } from "./fix-request.js";

/**
 * Security agent session requests discriminated by `request`.
 */
export type AgentSecurityRequest = FindRequest | FixRequest;
