/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Network egress mode. Set via the `"allowlist": "disabled"` short form;
 *
 * @remarks
 * must be the only rule in the allowlist and cannot be combined with
 * `domain`, `transform` or `credential`.
 */
export type AllowlistEntryMode = "disabled";

/**
 * Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
 */
export type Transform = Array<{ [k: string]: string }> | {
  [k: string]: string;
};

/**
 * A single domain allowlist rule with optional header injection.
 */
export type AllowlistEntry = {
  /**
   * Optional. Reference to a server-managed Credential resource by ID.
   */
  credential?: string | undefined;
  /**
   * Domain to allow outbound requests to. Supports wildcards (e.g.
   *
   * @remarks
   * '*.googleapis.com'). Use '*' to allow all domains.
   */
  domain: string;
  /**
   * Network egress mode. Set via the `"allowlist": "disabled"` short form;
   *
   * @remarks
   * must be the only rule in the allowlist and cannot be combined with
   * `domain`, `transform` or `credential`.
   */
  mode?: AllowlistEntryMode | undefined;
  /**
   * Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
   */
  transform?:
    | Array<{ [k: string]: string }>
    | { [k: string]: string }
    | undefined;
};
