/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
 */
export type Transform = Array<{ [k: string]: string }> | {
  [k: string]: string;
};

/**
 * A network egress rule that controls which external domains the
 *
 * @remarks
 * environment is allowed to reach.  Each rule identifies a target domain
 * and, optionally, a set of HTTP headers to inject into every matching
 * outbound request.
 */
export type AllowlistEntry = {
  /**
   * The domain pattern to match for this rule.
   *
   * @remarks
   * Use an exact hostname (e.g., `github.com`), a wildcard prefix
   * (e.g., `*.googleapis.com`), or `*` to match all domains.
   */
  domain: string;
  /**
   * Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
   */
  transform?:
    | Array<{ [k: string]: string }>
    | { [k: string]: string }
    | undefined;
};
