/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AllowlistEntry } from "./allowlist-entry.js";

/**
 * Network egress configuration for the environment.
 */
export type Allowlist = {
  /**
   * List of allowed domains and their configurations.
   */
  allowlist?: Array<AllowlistEntry> | undefined;
};
