/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
 */
export type Transform =
  | { [k: string]: string }
  | Array<{ [k: string]: string }>;

/**
 * A single domain allowlist rule with optional header injection.
 */
export type AllowlistEntry = {
  /**
   * Domain to allow outbound requests to. Supports wildcards (e.g. '*.googleapis.com'). Use '*' to allow all domains.
   */
  domain: string;
  /**
   * Headers to inject on all outbound requests matching this domain. Accepts a single dict or a list of dicts. The egress proxy injects these automatically.
   */
  transform?:
    | { [k: string]: string }
    | Array<{ [k: string]: string }>
    | undefined;
};
