/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for the Antigravity agent runtime.
 *
 * @remarks
 * Provides server-side control over the agent's execution environment
 * and tool configuration.
 */
export type AntigravityAgentConfig = {
  /**
   * Max total tokens for the agent run.
   */
  max_total_tokens?: string | undefined;
  type: "antigravity";
};
