/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CodeExecutionCallArguments } from "./code-execution-call-arguments.js";

export type CodeExecutionCallDelta = {
  /**
   * The arguments to pass to the code execution.
   */
  arguments: CodeExecutionCallArguments;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "code_execution_call";
};
