/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FileContent } from "./file-content.js";

/**
 * The mode of the find session.
 */
export type Mode = "scan" | "verify" | (string & {});

/**
 * Parameters for finding vulnerabilities.
 */
export type FindRequest = {
  /**
   * A list of source files to provide as context for the scan.
   */
  source_files?: Array<FileContent> | undefined;
  /**
   * The identifier of a specific finding to verify. This is primarily used in
   *
   * @remarks
   * VERIFY mode to focus the agent's execution-based validation on a single
   * vulnerability.
   */
  finding_id?: string | undefined;
  /**
   * Additional context or custom instructions provided by the user to guide
   *
   * @remarks
   * the vulnerability analysis.
   */
  description?: string | undefined;
  /**
   * The mode of the find session.
   */
  mode?: Mode | undefined;
};

/**
 * Parameters for fixing vulnerabilities.
 */
export type FixRequest = {
  /**
   * A list of source files providing context for the remediation. These files
   *
   * @remarks
   * are typically the ones containing the identified vulnerability.
   */
  source_files?: Array<FileContent> | undefined;
  /**
   * The identifier of the specific security finding to be remediated. This ID
   *
   * @remarks
   * maps to a previously discovered vulnerability.
   */
  finding_id?: string | undefined;
  /**
   * Additional context or custom instructions provided by the user to guide
   *
   * @remarks
   * the patch generation process.
   */
  description?: string | undefined;
};

/**
 * Optional session-specific configurations to override default agent
 *
 * @remarks
 * behavior.
 */
export type SessionConfig = {
  /**
   * The maximum number of interaction rounds the agent is allowed to perform
   *
   * @remarks
   * before reaching a timeout.
   */
  max_rounds?: number | undefined;
};

/**
 * Configuration for the CodeMender agent.
 */
export type CodeMenderAgentConfig = {
  type: "code-mender";
  /**
   * Parameters for finding vulnerabilities.
   */
  find_request?: FindRequest | undefined;
  /**
   * Parameters for fixing vulnerabilities.
   */
  fix_request?: FixRequest | undefined;
  /**
   * Parameter for grouping multiple interactions that belong to
   *
   * @remarks
   * the same CodeMender session.
   */
  session_id?: string | undefined;
  /**
   * Optional session-specific configurations to override default agent
   *
   * @remarks
   * behavior.
   */
  session_config?: SessionConfig | undefined;
  /**
   * The name of the model to use for the CodeMender agent. One
   *
   * @remarks
   * CodeMender session will only use one model.
   */
  model?: string | undefined;
};
