/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The environment being operated.
 */
export type EnvironmentEnum = "browser" | "mobile" | "desktop" | (string & {});

/**
 * A tool that can be used by the model to interact with the computer.
 */
export type ComputerUse = {
  type: "computer_use";
  /**
   * The environment being operated.
   */
  environment?: EnvironmentEnum | undefined;
  /**
   * The list of predefined functions that are excluded from the model call.
   */
  excluded_predefined_functions?: Array<string> | undefined;
  /**
   * Whether enable the prompt injection detection check on computer-use
   *
   * @remarks
   * request.
   */
  enable_prompt_injection_detection?: boolean | undefined;
};
