/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type CompositeMediaBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type CompositeMediaObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type CompositeMediaReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * A sequence of media data references representing composite data.
 *
 * @remarks
 * Introduced to support Bigstore composite objects. For details, visit
 * http://go/bigstore-composites.
 */
export type CompositeMedia = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: CompositeMediaBlobstore2Info | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: CompositeMediaObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: CompositeMediaReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};
