/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Environment } from "./environment.js";
import { GenerationConfig } from "./generation-config.js";
import { InteractionsInput } from "./interactions-input.js";
import { LocalEnvironmentConfig } from "./local-environment-config.js";
import { Model } from "./model.js";
import { ResponseFormat } from "./response-format.js";
import { ResponseModality } from "./response-modality.js";
import { SafetySetting } from "./safety-setting.js";
import { ServiceTier } from "./service-tier.js";
import { Tool } from "./tool.js";
import { WebhookConfig } from "./webhook-config.js";

/**
 * The environment configuration for the interaction.
 */
export type CreateModelInteractionEnvironment =
  | Environment
  | LocalEnvironmentConfig
  | string;

export type CreateModelInteractionResponseFormat =
  | ResponseFormat
  | Array<ResponseFormat>;

/**
 * Interaction for generating the completion using models.
 */
export type CreateModelInteraction = {
  /**
   * Input only. Whether to run the model interaction in the background.
   */
  background?: boolean | undefined;
  /**
   * The name of the cached content used as context to serve the prediction. Note: only used in explicit caching, where users can have control over caching (e.g. what content to cache) and enjoy guaranteed cost savings. Format: cachedContents/{cachedContent}
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  cached_content?: string | undefined;
  /**
   * The environment configuration for the interaction.
   */
  environment?: Environment | LocalEnvironmentConfig | string | undefined;
  /**
   * Configuration parameters for model interactions.
   */
  generation_config?: GenerationConfig | undefined;
  /**
   * The input for the interaction.
   */
  input?: InteractionsInput | undefined;
  /**
   * The labels with user-defined metadata for the request. It is used for
   *
   * @remarks
   * billing and reporting only.
   *
   * Label keys and values can be no longer than 63 characters
   * (Unicode codepoints) and can only contain lowercase letters, numeric
   * characters, underscores, and dashes. International characters are allowed.
   * Label values are optional. Label keys must start with a letter.
   */
  labels?: { [k: string]: string } | undefined;
  /**
   * The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
   */
  model: Model;
  /**
   * The ID of the previous interaction, if any.
   */
  previous_interaction_id?: string | undefined;
  response_format?: ResponseFormat | Array<ResponseFormat> | undefined;
  /**
   * The mime type of the response. This is required if response_format is set.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_mime_type?: string | undefined;
  /**
   * The requested modalities of the response (TEXT, IMAGE, AUDIO).
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_modalities?: Array<ResponseModality> | undefined;
  /**
   * Safety settings for the interaction.
   */
  safety_settings?: Array<SafetySetting> | undefined;
  service_tier?: ServiceTier | undefined;
  /**
   * Input only. Whether to store the response and request for later retrieval.
   */
  store?: boolean | undefined;
  /**
   * Input only. Whether the interaction will be streamed.
   */
  stream?: boolean | undefined;
  /**
   * System instruction for the interaction.
   */
  system_instruction?: string | undefined;
  /**
   * A list of tool declarations the model may call during interaction.
   */
  tools?: Array<Tool> | undefined;
  /**
   * Message for configuring webhook events for a request.
   */
  webhook_config?: WebhookConfig | undefined;
};
