/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CreateAgentInteraction } from "./create-agent-interaction.js";
import { CreateModelInteraction } from "./create-model-interaction.js";

/**
 * Configuration parameters for creating an interaction.
 */
export type CreateInteractionRequest =
  | CreateAgentInteraction
  | CreateModelInteraction;
