/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AgentOption } from "./agent-option.js";
import { DeepResearchAgentConfig } from "./deep-research-agent-config.js";
import { DynamicAgentConfig } from "./dynamic-agent-config.js";
import { Environment } from "./environment.js";
import { InteractionsInput } from "./interactions-input.js";
import { ResponseFormat } from "./response-format.js";
import { ResponseModality } from "./response-modality.js";
import { ServiceTier } from "./service-tier.js";
import { Tool } from "./tool.js";
import { Usage } from "./usage.js";
import { WebhookConfig } from "./webhook-config.js";

/**
 * The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
 */
export type CreateAgentInteractionEnvironment = Environment | string;

/**
 * Configuration parameters for the agent interaction.
 */
export type CreateAgentInteractionAgentConfig =
  | DynamicAgentConfig
  | DeepResearchAgentConfig;

/**
 * Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
 */
export type CreateAgentInteractionResponseFormat =
  | Array<ResponseFormat>
  | ResponseFormat;

/**
 * Parameters for creating agent interactions
 */
export type CreateAgentInteraction = {
  /**
   * The agent to interact with.
   */
  agent: AgentOption;
  /**
   * Input only. Whether to run the model interaction in the background.
   */
  background?: boolean | undefined;
  /**
   * Input only. Whether to store the response and request for later retrieval.
   */
  store?: boolean | undefined;
  /**
   * Input only. Whether the interaction will be streamed.
   */
  stream?: boolean | undefined;
  /**
   * The environment configuration for the interaction. Can be an object specifying remote environment sources or a string referencing an existing environment ID.
   */
  environment?: Environment | string | undefined;
  /**
   * The ID of the previous interaction, if any.
   */
  previous_interaction_id?: string | undefined;
  /**
   * The mime type of the response. This is required if response_format is set.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_mime_type?: string | undefined;
  /**
   * The requested modalities of the response (TEXT, IMAGE, AUDIO).
   */
  response_modalities?: Array<ResponseModality> | undefined;
  service_tier?: ServiceTier | undefined;
  /**
   * System instruction for the interaction.
   */
  system_instruction?: string | undefined;
  /**
   * A list of tool declarations the model may call during interaction.
   */
  tools?: Array<Tool> | undefined;
  /**
   * Statistics on the interaction request's token usage.
   */
  usage?: Usage | undefined;
  /**
   * Message for configuring webhook events for a request.
   */
  webhook_config?: WebhookConfig | undefined;
  /**
   * Configuration parameters for the agent interaction.
   */
  agent_config?: DynamicAgentConfig | DeepResearchAgentConfig | undefined;
  /**
   * Enforces that the generated response is a JSON object that complies with the JSON schema specified in this field.
   */
  response_format?: Array<ResponseFormat> | ResponseFormat | undefined;
  /**
   * The input for the interaction.
   */
  input: InteractionsInput;
};
