/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Allowlist } from "./allowlist.js";

/**
 * Turns all network off.
 */
export type Disabled = "disabled";

/**
 * Outbound networking configuration for the sandbox. Accepts an object with an 'allowlist' array to restrict traffic, or the string 'disabled' to turn off all network access. Omit entirely to allow all outbound traffic with no header injection.
 */
export type EnvironmentNetworkEgressAllowlist = Allowlist | Disabled;
