/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AllowlistEntry } from "./allowlist-entry.js";

export type Disabled = "disabled";

/**
 * List of allowed domains and their configurations. Set to `"disabled"`
 *
 * @remarks
 * to block all network egress.
 */
export type Allowlist = Array<AllowlistEntry> | Disabled;

/**
 * Network egress configuration for the environment.
 */
export type EnvironmentNetworkEgressAllowlist = {
  /**
   * List of allowed domains and their configurations. Set to `"disabled"`
   *
   * @remarks
   * to block all network egress.
   */
  allowlist?: Array<AllowlistEntry> | Disabled | undefined;
};
