/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { EnvVar } from "./env-var.js";
import { EnvironmentNetworkEgressAllowlist } from "./environment-network-egress-allowlist.js";
import { Source } from "./source.js";

/**
 * Environment variables to set in the sandbox environment.
 */
export type Env = { [k: string]: EnvVar } | string;

export type NetworkEnum = "disabled";

/**
 * Network configuration for the environment.
 */
export type Network = EnvironmentNetworkEgressAllowlist | NetworkEnum;

/**
 * Configuration for a custom environment.
 */
export type Environment = {
  /**
   * Environment variables to set in the sandbox environment.
   */
  env?: { [k: string]: EnvVar } | string | undefined;
  /**
   * Optional. The environment ID for the interaction. If specified, the request will
   *
   * @remarks
   * update the existing environment instead of creating a new one.
   */
  environment_id?: string | undefined;
  /**
   * Network configuration for the environment.
   */
  network?: EnvironmentNetworkEgressAllowlist | NetworkEnum | undefined;
  sources?: Array<Source> | undefined;
  type: "remote";
};
