/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ErrorT } from "./error.js";
import { Usage } from "./usage.js";

/**
 * Optional metadata accompanying ANY streamed event.
 */
export type ErrorEventMetadata = {
  /**
   * Statistics on the interaction request's token usage.
   */
  total_usage?: Usage | undefined;
};

export type ErrorEvent = {
  event_type: "error";
  /**
   * Error message from an interaction.
   */
  error?: ErrorT | undefined;
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  /**
   * Optional metadata accompanying ANY streamed event.
   */
  metadata?: ErrorEventMetadata | undefined;
};
