/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type FileSearchCallDelta = {
  /**
   * Required. A unique ID for this specific tool call.
   */
  id?: string | undefined;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "file_search_call";
};
