/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Content of a single file in the codebase.
 */
export type FileContent = {
  /**
   * The relative path of the file from the project root.
   */
  path?: string | undefined;
  /**
   * The UTF-8 encoded text content of the file.
   */
  content?: string | undefined;
};
