/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type Operator = "equals" | "in" | (string & {});

/**
 * A single declarative filter rule for webhook payload evaluation.
 */
export type FilterRule = {
  /**
   * Required. JSON path in the payload to evaluate (e.g., "payload.action").
   *
   * @remarks
   * Uses dot notation for nested fields.
   */
  field_path: string;
  operator: Operator;
  /**
   * Required. Values to match against. For EQUALS, only values[0] is used.
   */
  values: Array<string>;
};
