/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FileContent } from "./file-content.js";
import { SessionConfig } from "./session-config.js";

/**
 * Request parameters specific to FIND sessions, used for discovering
 *
 * @remarks
 * vulnerabilities in a codebase.
 */
export type FindRequest = {
  request: "find_request";
  /**
   * A list of source files to provide as context for the scan.
   */
  source_files?: Array<FileContent> | undefined;
  /**
   * The identifier of a specific finding to verify. This is primarily used in
   *
   * @remarks
   * VERIFY mode to focus the agent's execution-based validation on a single
   * vulnerability.
   */
  finding_id?: string | undefined;
  /**
   * Additional context or custom instructions provided by the user to guide
   *
   * @remarks
   * the vulnerability analysis.
   */
  description?: string | undefined;
  /**
   * Parameter for grouping multiple interactions that belong to
   *
   * @remarks
   * the same CodeMender session.
   */
  session_id?: string | undefined;
  /**
   * The configuration of CodeMender sessions.
   */
  session_config?: SessionConfig | undefined;
  /**
   * The name of the model to use for the CodeMender agent. One
   *
   * @remarks
   * CodeMender session will only use one model.
   */
  model?: string | undefined;
};
