/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FileContent } from "./file-content.js";
import { SessionConfig } from "./session-config.js";

/**
 * Request parameters specific to FIX sessions, used for generating and
 *
 * @remarks
 * validating security patches.
 */
export type FixRequest = {
  request: "fix_request";
  /**
   * A list of source files providing context for the remediation. These files
   *
   * @remarks
   * are typically the ones containing the identified vulnerability.
   */
  source_files?: Array<FileContent> | undefined;
  /**
   * The identifier of the specific security finding to be remediated. This ID
   *
   * @remarks
   * maps to a previously discovered vulnerability.
   */
  finding_id?: string | undefined;
  /**
   * Additional context or custom instructions provided by the user to guide
   *
   * @remarks
   * the patch generation process.
   */
  description?: string | undefined;
  /**
   * Parameter for grouping multiple interactions that belong to
   *
   * @remarks
   * the same CodeMender session.
   */
  session_id?: string | undefined;
  /**
   * The configuration of CodeMender sessions.
   */
  session_config?: SessionConfig | undefined;
  /**
   * The name of the model to use for the CodeMender agent. One
   *
   * @remarks
   * CodeMender session will only use one model.
   */
  model?: string | undefined;
};
