/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A tool that can be used by the model.
 */
export type FunctionT = {
  /**
   * If true, the function's loading is deferred.
   */
  defer_loading?: boolean | undefined;
  /**
   * A description of the function.
   */
  description?: string | undefined;
  /**
   * The name of the function.
   */
  name?: string | undefined;
  /**
   * The JSON Schema for the function's parameters.
   */
  parameters?: any | undefined;
  /**
   * A brief description of the function, shown to the model as a
   *
   * @remarks
   * short summary of functions with `defer_loading` set to true.
   */
  short_description?: string | undefined;
  type: "function";
};
