/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ImageConfig } from "./image-config.js";
import { SpeechConfig } from "./speech-config.js";
import { ThinkingLevel } from "./thinking-level.js";
import { ThinkingSummaries } from "./thinking-summaries.js";
import { ToolChoiceConfig } from "./tool-choice-config.js";
import { ToolChoiceType } from "./tool-choice-type.js";

/**
 * The tool choice configuration.
 */
export type ToolChoice = ToolChoiceType | ToolChoiceConfig;

/**
 * Configuration parameters for model interactions.
 */
export type GenerationConfig = {
  /**
   * The configuration for image interaction.
   */
  image_config?: ImageConfig | undefined;
  /**
   * The maximum number of tokens to include in the response.
   */
  max_output_tokens?: number | undefined;
  /**
   * Seed used in decoding for reproducibility.
   */
  seed?: number | undefined;
  /**
   * Configuration for speech interaction.
   */
  speech_config?: Array<SpeechConfig> | undefined;
  /**
   * A list of character sequences that will stop output interaction.
   */
  stop_sequences?: Array<string> | undefined;
  /**
   * Controls the randomness of the output.
   */
  temperature?: number | undefined;
  thinking_level?: ThinkingLevel | undefined;
  thinking_summaries?: ThinkingSummaries | undefined;
  /**
   * The tool choice configuration.
   */
  tool_choice?: ToolChoiceType | ToolChoiceConfig | undefined;
  /**
   * The maximum cumulative probability of tokens to consider when sampling.
   */
  top_p?: number | undefined;
};
