/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CompositeMedia } from "./composite-media.js";
import { EnvironmentFile } from "./environment-file.js";

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type GetEnvironmentFilesResponseBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Extended content type information provided for Scotty uploads.
 */
export type ContentTypeInfo = {
  /**
   * Scotty's best guess of what the content type of the file is.
   */
  best_guess?: string | undefined;
  /**
   * The content type of the file derived by looking at specific
   *
   * @remarks
   * bytes (i.e. "magic bytes") of the actual file.
   */
  from_bytes?: string | undefined;
  /**
   * The content type of the file derived from the file extension of
   *
   * @remarks
   * the original file name used by the client.
   */
  from_file_name?: string | undefined;
  /**
   * The content type of the file detected by Fusion ID. go/fusionid
   */
  from_fusion_id?: string | undefined;
  /**
   * The content type of the file as specified in the request headers,
   *
   * @remarks
   * multipart headers, or RUPIO start request.
   */
  from_header?: string | undefined;
  /**
   * The content type of the file derived from the file extension of the
   *
   * @remarks
   * URL path.  The URL path is assumed to represent a file name (which
   * is typically only true for agents that are providing a REST API).
   */
  from_url_path?: string | undefined;
  /**
   * Metadata information from Fusion ID detection. Serialized
   *
   * @remarks
   * FusionIdDetectionMetadata proto. Only set if from_fusion_id is set.
   */
  fusion_id_detection_metadata?: string | undefined;
};

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type ChecksumsLocationBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type ChecksumsLocationObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type ChecksumsLocationReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * Exactly one of these fields must be populated.
 *
 * @remarks
 *
 * If checksums_location is filled, the server will return the corresponding
 * contents to the user.  If object_location is filled, the server will
 * calculate the checksums based on the content there and return that to the
 * user.
 * For details on the format of the checksums,
 * see http://go/scotty-diff-protocol.
 */
export type ChecksumsLocation = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: ChecksumsLocationBlobstore2Info | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: ChecksumsLocationObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: ChecksumsLocationReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type DiffChecksumsResponseObjectLocationBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type DiffChecksumsResponseObjectLocationObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type DiffChecksumsResponseObjectLocationReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * If set, calculate the checksums based on the contents and return them to
 *
 * @remarks
 * the caller.
 */
export type DiffChecksumsResponseObjectLocation = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?:
    | DiffChecksumsResponseObjectLocationBlobstore2Info
    | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: DiffChecksumsResponseObjectLocationObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: DiffChecksumsResponseObjectLocationReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};

/**
 * Set if reference_type is DIFF_CHECKSUMS_RESPONSE.
 */
export type DiffChecksumsResponse = {
  /**
   * Exactly one of these fields must be populated.
   *
   * @remarks
   *
   * If checksums_location is filled, the server will return the corresponding
   * contents to the user.  If object_location is filled, the server will
   * calculate the checksums based on the content there and return that to the
   * user.
   * For details on the format of the checksums,
   * see http://go/scotty-diff-protocol.
   */
  checksums_location?: ChecksumsLocation | undefined;
  /**
   * The chunk size of checksums.  Must be a multiple of 256KB.
   */
  chunk_size_bytes?: string | undefined;
  /**
   * If set, calculate the checksums based on the contents and return them to
   *
   * @remarks
   * the caller.
   */
  object_location?: DiffChecksumsResponseObjectLocation | undefined;
  /**
   * The total size of the server object.
   */
  object_size_bytes?: string | undefined;
  /**
   * The object version of the object the checksums are being returned for.
   */
  object_version?: string | undefined;
};

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type DiffDownloadResponseBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type DiffDownloadResponseObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type DiffDownloadResponseReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * The original object location.
 */
export type DiffDownloadResponseObjectLocation = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: DiffDownloadResponseBlobstore2Info | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: DiffDownloadResponseObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: DiffDownloadResponseReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};

/**
 * Set if reference_type is DIFF_DOWNLOAD_RESPONSE.
 */
export type DiffDownloadResponse = {
  /**
   * The original object location.
   */
  object_location?: DiffDownloadResponseObjectLocation | undefined;
};

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type ChecksumsInfoBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type ChecksumsInfoObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type ChecksumsInfoReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * The location of the checksums for the new object.
 *
 * @remarks
 * Agents must clone the object located here, as the upload server will
 * delete the contents once a response is received.
 * For details on the format of the checksums,
 * see http://go/scotty-diff-protocol.
 */
export type ChecksumsInfo = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: ChecksumsInfoBlobstore2Info | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: ChecksumsInfoObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: ChecksumsInfoReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type ObjectInfoBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type ObjectInfoObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type ObjectInfoReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * The location of the new object.
 *
 * @remarks
 * Agents must clone the object located here, as the upload server will
 * delete the contents once a response is received.
 */
export type ObjectInfo = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: ObjectInfoBlobstore2Info | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: ObjectInfoObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: ObjectInfoReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};

/**
 * Set if reference_type is DIFF_UPLOAD_REQUEST.
 */
export type DiffUploadRequest = {
  /**
   * The location of the checksums for the new object.
   *
   * @remarks
   * Agents must clone the object located here, as the upload server will
   * delete the contents once a response is received.
   * For details on the format of the checksums,
   * see http://go/scotty-diff-protocol.
   */
  checksums_info?: ChecksumsInfo | undefined;
  /**
   * The location of the new object.
   *
   * @remarks
   * Agents must clone the object located here, as the upload server will
   * delete the contents once a response is received.
   */
  object_info?: ObjectInfo | undefined;
  /**
   * The object version of the object that is the base version the incoming
   *
   * @remarks
   * diff script will be applied to.
   * This field will always be filled in.
   */
  object_version?: string | undefined;
};

/**
 * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
 *
 * @remarks
 * to a v2 blob.
 */
export type OriginalObjectBlobstore2Info = {
  /**
   * The blob generation id.
   */
  blob_generation?: string | undefined;
  /**
   * The blob id, e.g., /blobstore/prod/playground/scotty
   */
  blob_id?: string | undefined;
  /**
   * A serialized External Read Token passed from Bigstore -> Scotty for a GCS
   *
   * @remarks
   * download. This field must never be consumed outside of Bigstore, and is not
   * applicable to non-GCS media uploads.
   */
  download_external_read_token?: string | undefined;
  /**
   * Read handle passed from Bigstore -> Scotty for a GCS download.
   *
   * @remarks
   * This is a signed, serialized blobstore2.ReadHandle proto which must never
   * be set outside of Bigstore, and is not applicable to non-GCS media
   * downloads.
   */
  download_read_handle?: string | undefined;
  /**
   * The blob read token. Needed to read blobs that have not been
   *
   * @remarks
   * replicated. Might not be available until the final call.
   */
  read_token?: string | undefined;
  /**
   * A serialized Object Fragment List Creation Info passed from Bigstore ->
   *
   * @remarks
   * Scotty for a GCS upload. This field must never be consumed outside of
   * Bigstore, and is not applicable to non-GCS media uploads.
   */
  upload_fragment_list_creation_info?: string | undefined;
  /**
   * Metadata passed from Blobstore -> Scotty for a new GCS upload.
   *
   * @remarks
   * This is a signed, serialized blobstore2.BlobMetadataContainer proto which
   * must never be consumed outside of Bigstore, and is not applicable to
   * non-GCS media uploads.
   */
  upload_metadata_container?: string | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type OriginalObjectObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type OriginalObjectReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "bigstore_ref"
  | "cosmo_binary_reference"
  | (string & {});

/**
 * The location of the original file for a diff upload request. Must be
 *
 * @remarks
 * filled in if responding to an upload start notification.
 */
export type OriginalObject = {
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: OriginalObjectBlobstore2Info | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * crc32.c hash for the payload.
   */
  crc32c_hash?: number | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * MD5 hash for the payload.
   */
  md5_hash?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: OriginalObjectObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: OriginalObjectReferenceType | undefined;
  /**
   * SHA-1 hash for the payload.
   */
  sha1_hash?: string | undefined;
};

/**
 * Set if reference_type is DIFF_UPLOAD_RESPONSE.
 */
export type DiffUploadResponse = {
  /**
   * The object version of the object at the server. Must be included in the
   *
   * @remarks
   * end notification response.
   * The version in the end notification response must correspond to the new
   * version of the object that is now stored at the server, after the upload.
   */
  object_version?: string | undefined;
  /**
   * The location of the original file for a diff upload request. Must be
   *
   * @remarks
   * filled in if responding to an upload start notification.
   */
  original_object?: OriginalObject | undefined;
};

/**
 * Set if reference_type is DIFF_VERSION_RESPONSE.
 */
export type DiffVersionResponse = {
  /**
   * The total size of the server object.
   */
  object_size_bytes?: string | undefined;
  /**
   * The version of the object stored at the server.
   */
  object_version?: string | undefined;
};

/**
 * Parameters for a media download.
 */
export type DownloadParameters = {
  /**
   * A boolean to be returned in the response to Scotty. Allows/disallows gzip
   *
   * @remarks
   * encoding of the payload content when the server thinks it's
   * advantageous (hence, does not guarantee compression) which allows
   * Scotty to GZip the response to the client.
   */
  allow_gzip_compression?: boolean | undefined;
  /**
   * Determining whether or not Apiary should skip the inclusion
   *
   * @remarks
   * of any Content-Range header on its response to Scotty.
   */
  ignore_range?: boolean | undefined;
};

/**
 * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
 */
export type GetEnvironmentFilesResponseObjectId = {
  /**
   * The name of the bucket to which this object belongs.
   */
  bucket_name?: string | undefined;
  /**
   * Generation of the object. Generations are monotonically increasing
   *
   * @remarks
   * across writes, allowing them to be be compared to determine which
   * generation is newer. If this is omitted in a request, then you are
   * requesting the live object.
   * See http://go/bigstore-versions
   */
  generation?: string | undefined;
  /**
   * The name of the object.
   */
  object_name?: string | undefined;
};

/**
 * Describes what the field reference contains.
 */
export type GetEnvironmentFilesResponseReferenceType =
  | "path"
  | "blob_ref"
  | "inline"
  | "get_media"
  | "composite_media"
  | "bigstore_ref"
  | "diff_version_response"
  | "diff_checksums_response"
  | "diff_download_response"
  | "diff_upload_request"
  | "diff_upload_response"
  | "cosmo_binary_reference"
  | "arbitrary_bytes"
  | (string & {});

/**
 * Reference to the file content. Only populated and used by ESF/Scotty
 *
 * @remarks
 * during media downloads (alt=media). Hidden from public JSON API responses.
 */
export type BlobT = {
  /**
   * Deprecated, use one of explicit hash type fields instead.
   *
   * @remarks
   * Algorithm used for calculating the hash.
   * As of 2011/01/21, "MD5" is the only possible value for this field.
   * New values may be added at any time.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  algorithm?: string | undefined;
  /**
   * Use object_id instead.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  bigstore_object_ref?: string | undefined;
  /**
   * Blobstore v1 reference, set if reference_type is BLOBSTORE_REF
   *
   * @remarks
   * This should be the byte representation of a blobstore.BlobRef.
   * Since Blobstore is deprecating v1, use blobstore2_info instead.
   * For now, any v2 blob will also be represented in this field as
   * v1 BlobRef.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  blob_ref?: string | undefined;
  /**
   * Blobstore v2 info, set if reference_type is BLOBSTORE_REF and it refers
   *
   * @remarks
   * to a v2 blob.
   */
  blobstore2_info?: GetEnvironmentFilesResponseBlobstore2Info | undefined;
  /**
   * A composite media composed of one or more media objects, set if
   *
   * @remarks
   * reference_type is COMPOSITE_MEDIA. The media length field must be set
   * to the sum of the lengths of all composite media objects.
   *
   * Note: All composite media must have length specified.
   */
  composite_media?: Array<CompositeMedia> | undefined;
  /**
   * MIME type of the data
   */
  content_type?: string | undefined;
  /**
   * Extended content type information provided for Scotty uploads.
   */
  content_type_info?: ContentTypeInfo | undefined;
  /**
   * A binary data reference for a media download. Serves as a
   *
   * @remarks
   * technology-agnostic binary reference in some Google infrastructure.
   * This value is a serialized storage_cosmo.BinaryReference proto. Storing
   * it as bytes is a hack to get around the fact that the cosmo proto
   * (as well as others it includes) doesn't support JavaScript. This
   * prevents us from including the actual type of this field.
   */
  cosmo_binary_reference?: string | undefined;
  /**
   * For Scotty Uploads:
   *
   * @remarks
   * Scotty-provided hashes for uploads
   *
   * For Scotty Downloads:
   * (WARNING: DO NOT USE WITHOUT PERMISSION FROM THE SCOTTY TEAM.)
   * A Hash provided by the agent to be used to verify the data being
   * downloaded. Currently only supported for inline payloads.
   * Further, only crc32c_hash is currently supported.
   */
  crc32c_hash?: number | undefined;
  /**
   * Set if reference_type is DIFF_CHECKSUMS_RESPONSE.
   */
  diff_checksums_response?: DiffChecksumsResponse | undefined;
  /**
   * Set if reference_type is DIFF_DOWNLOAD_RESPONSE.
   */
  diff_download_response?: DiffDownloadResponse | undefined;
  /**
   * Set if reference_type is DIFF_UPLOAD_REQUEST.
   */
  diff_upload_request?: DiffUploadRequest | undefined;
  /**
   * Set if reference_type is DIFF_UPLOAD_RESPONSE.
   */
  diff_upload_response?: DiffUploadResponse | undefined;
  /**
   * Set if reference_type is DIFF_VERSION_RESPONSE.
   */
  diff_version_response?: DiffVersionResponse | undefined;
  /**
   * Parameters for a media download.
   */
  download_parameters?: DownloadParameters | undefined;
  /**
   * Original file name
   */
  filename?: string | undefined;
  /**
   * Deprecated, use one of explicit hash type fields instead.
   *
   * @remarks
   * These two hash related fields will only be populated on Scotty based media
   * uploads and will contain the content of the hash group in the
   * NotificationRequest:
   * http://cs/#google3/blobstore2/api/scotty/service/proto/upload_listener.proto&q=class:Hash
   * Hex encoded hash value of the uploaded media.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  hash?: string | undefined;
  /**
   * For Scotty uploads only. If a user sends a hash code and the backend has
   *
   * @remarks
   * requested that Scotty verify the upload against the client hash,
   * Scotty will perform the check on behalf of the backend and will reject it
   * if the hashes don't match. This is set to true if Scotty performed
   * this verification.
   */
  hash_verified?: boolean | undefined;
  /**
   * Media data, set if reference_type is INLINE
   */
  inline?: string | undefined;
  /**
   * |is_potential_retry| is set false only when Scotty is
   *
   * @remarks
   * certain that it has not sent the request before. When a client resumes
   * an upload, this field must be set true in agent calls, because Scotty
   * cannot be certain that it has never sent the request before due
   * to potential failure in the session state persistence.
   */
  is_potential_retry?: boolean | undefined;
  /**
   * Size of the data, in bytes
   */
  length?: string | undefined;
  /**
   * Scotty-provided MD5 hash for an upload.
   */
  md5_hash?: string | undefined;
  /**
   * Media id to forward to the operation GetMedia.
   *
   * @remarks
   * Can be set if reference_type is GET_MEDIA.
   */
  media_id?: string | undefined;
  /**
   * Reference to a TI Blob, set if reference_type is BIGSTORE_REF.
   */
  object_id?: GetEnvironmentFilesResponseObjectId | undefined;
  /**
   * Path to the data, set if reference_type is PATH
   */
  path?: string | undefined;
  /**
   * Describes what the field reference contains.
   */
  reference_type?: GetEnvironmentFilesResponseReferenceType | undefined;
  /**
   * Scotty-provided SHA1 hash for an upload.
   */
  sha1_hash?: string | undefined;
  /**
   * Scotty-provided SHA256 hash for an upload.
   */
  sha256_hash?: string | undefined;
  /**
   * Scotty-provided SHA512 hash for an upload.
   */
  sha512_hash?: string | undefined;
  /**
   * Time at which the media data was last updated,
   *
   * @remarks
   * in milliseconds since UNIX epoch
   */
  timestamp?: string | undefined;
  /**
   * A unique fingerprint/version id for the media data
   */
  token?: string | undefined;
};

/**
 * Response for `GetEnvironmentFiles`.
 */
export type GetEnvironmentFilesResponse = {
  /**
   * Reference to the file content. Only populated and used by ESF/Scotty
   *
   * @remarks
   * during media downloads (alt=media). Hidden from public JSON API responses.
   */
  blob?: BlobT | undefined;
  /**
   * If the requested path is a directory, this contains its contents.
   *
   * @remarks
   * If the requested path is a file, this contains a single entry with the
   * file's metadata.
   * If alt=media was specified, this is empty (content is served via `blob`).
   */
  files?: Array<EnvironmentFile> | undefined;
  /**
   * Pagination token for directory listing.
   */
  next_page_token?: string | undefined;
};
