/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type HarmCategory =
  | "hate_speech"
  | "dangerous_content"
  | "harassment"
  | "sexually_explicit"
  | "civic_integrity"
  | "image_hate"
  | "image_dangerous_content"
  | "image_harassment"
  | "image_sexually_explicit"
  | "jailbreak"
  | (string & {});
