/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The aspect ratio of the image to generate. Supported aspect ratios: 1:1,
 *
 * @remarks
 * 2:3, 3:2, 3:4, 4:3, 9:16, 16:9, 21:9.
 *
 * If not specified, the model will choose a default aspect ratio based on any
 * reference images provided.
 */
export type ImageConfigAspectRatio =
  | "1:1"
  | "2:3"
  | "3:2"
  | "3:4"
  | "4:3"
  | "4:5"
  | "5:4"
  | "9:16"
  | "16:9"
  | "21:9"
  | "1:8"
  | "8:1"
  | "1:4"
  | "4:1"
  | (string & {});

/**
 * Specifies the size of generated images. Supported values are `1K`, `2K`,
 *
 * @remarks
 * `4K`. If not specified, the model will use default value `1K`.
 */
export type ImageConfigImageSize = "1K" | "2K" | "4K" | "512" | (string & {});

/**
 * The configuration for image interaction.
 */
export type ImageConfig = {
  /**
   * The aspect ratio of the image to generate. Supported aspect ratios: 1:1,
   *
   * @remarks
   * 2:3, 3:2, 3:4, 4:3, 9:16, 16:9, 21:9.
   *
   * If not specified, the model will choose a default aspect ratio based on any
   * reference images provided.
   */
  aspect_ratio?: ImageConfigAspectRatio | undefined;
  /**
   * Specifies the size of generated images. Supported values are `1K`, `2K`,
   *
   * @remarks
   * `4K`. If not specified, the model will use default value `1K`.
   */
  image_size?: ImageConfigImageSize | undefined;
};
