/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InteractionSseEventInteraction } from "./interaction-sse-event-interaction.js";

/**
 * Signals that the Interaction completed. Sent when the Interaction receives
 *
 * @remarks
 * Complete/Cancel or naturally terminates. No more input can be sent to the
 * Interaction after this.
 */
export type InteractionCompletedEvent = {
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "interaction.completed";
  /**
   * Partial interaction resource emitted by interaction lifecycle SSE events.
   *
   * @remarks
   * Streaming lifecycle payloads may omit fields that are only available on
   * full non-streaming Interaction responses.
   */
  interaction: InteractionSseEventInteraction;
};
