/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Output only. The status of the interaction.
 */
export type InteractionMetadataStatus =
  | "in_progress"
  | "requires_action"
  | "completed"
  | "failed"
  | "cancelled"
  | "incomplete"
  | "budget_exceeded"
  | "queued"
  | (string & {});

/**
 * Metadata for an interaction, used for listing interactions.
 */
export type InteractionMetadata = {
  /**
   * Output only. The time at which the response was created in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  created?: string | undefined;
  /**
   * Output only. A unique identifier for the interaction completion.
   */
  id?: string | undefined;
  /**
   * Output only. The status of the interaction.
   */
  status?: InteractionMetadataStatus | undefined;
  /**
   * Output only. The time at which the response was last updated in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  updated?: string | undefined;
};
