/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { StreamMetadata } from "./stream-metadata.js";

export type InteractionStatusUpdateStatus =
  | "in_progress"
  | "requires_action"
  | "completed"
  | "failed"
  | "cancelled"
  | "incomplete"
  | "budget_exceeded"
  | (string & {});

export type InteractionStatusUpdate = {
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "interaction.status_update";
  interaction_id: string;
  metadata?: StreamMetadata | undefined;
  status: InteractionStatusUpdateStatus;
};
