/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { AgentOption } from "./agent-option.js";
import { AntigravityAgentConfig } from "./antigravity-agent-config.js";
import { AudioContent } from "./audio-content.js";
import { CodeMenderAgentConfig } from "./code-mender-agent-config.js";
import { DeepResearchAgentConfig } from "./deep-research-agent-config.js";
import { DynamicAgentConfig } from "./dynamic-agent-config.js";
import { Environment } from "./environment.js";
import { ErrorT } from "./error.js";
import { GenerationConfig } from "./generation-config.js";
import { ImageContent } from "./image-content.js";
import { InteractionsInput } from "./interactions-input.js";
import { LocalEnvironmentConfig } from "./local-environment-config.js";
import { Model } from "./model.js";
import { ResponseFormat } from "./response-format.js";
import { ResponseModality } from "./response-modality.js";
import { SafetySetting } from "./safety-setting.js";
import { ServiceTier } from "./service-tier.js";
import { Step } from "./step.js";
import { Tool } from "./tool.js";
import { Usage } from "./usage.js";
import { VideoContent } from "./video-content.js";
import { WebhookConfig } from "./webhook-config.js";

/**
 * The environment configuration for the interaction.
 */
export type InteractionEnvironment =
  | Environment
  | LocalEnvironmentConfig
  | string;

export type InteractionResponseFormat = ResponseFormat | Array<ResponseFormat>;

/**
 * Required. Output only. The status of the interaction.
 */
export type InteractionStatus =
  | "in_progress"
  | "requires_action"
  | "completed"
  | "failed"
  | "cancelled"
  | "incomplete"
  | "budget_exceeded"
  | "queued"
  | (string & {});

/**
 * Parameters for the agent interaction.
 */
export type InteractionAgentConfig =
  | AntigravityAgentConfig
  | CodeMenderAgentConfig
  | DeepResearchAgentConfig
  | DynamicAgentConfig;

/**
 * The Interaction resource.
 */
export type Interaction = {
  /**
   * Required. Output only. The time at which the response was created in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  created?: string | undefined;
  /**
   * The environment configuration for the interaction.
   */
  environment?: Environment | LocalEnvironmentConfig | string | undefined;
  /**
   * Output only. The environment ID for the interaction. Only populated if environment
   *
   * @remarks
   * config is set in the request.
   */
  environment_id?: string | undefined;
  /**
   * Output only. Diagnostic faults / platform errors recorded on the interaction.
   */
  errors?: Array<ErrorT> | undefined;
  /**
   * Configuration parameters for model interactions.
   */
  generation_config?: GenerationConfig | undefined;
  /**
   * Required. Output only. A unique identifier for the interaction completion.
   */
  id?: string | undefined;
  /**
   * The labels with user-defined metadata for the request. It is used for
   *
   * @remarks
   * billing and reporting only.
   *
   * Label keys and values can be no longer than 63 characters
   * (Unicode codepoints) and can only contain lowercase letters, numeric
   * characters, underscores, and dashes. International characters are allowed.
   * Label values are optional. Label keys must start with a letter.
   */
  labels?: { [k: string]: string } | undefined;
  /**
   * The ID of the previous interaction, if any.
   */
  previous_interaction_id?: string | undefined;
  response_format?: ResponseFormat | Array<ResponseFormat> | undefined;
  /**
   * Safety settings for the interaction.
   */
  safety_settings?: Array<SafetySetting> | undefined;
  service_tier?: ServiceTier | undefined;
  /**
   * Required. Output only. The status of the interaction.
   */
  status: InteractionStatus;
  /**
   * Required. Output only. The steps that make up the interaction.
   */
  steps?: Array<Step> | undefined;
  /**
   * System instruction for the interaction.
   */
  system_instruction?: string | undefined;
  /**
   * A list of tool declarations the model may call during interaction.
   */
  tools?: Array<Tool> | undefined;
  /**
   * Required. Output only. The time at which the response was last updated in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  updated?: string | undefined;
  /**
   * Statistics on the interaction request's token usage.
   */
  usage?: Usage | undefined;
  /**
   * Message for configuring webhook events for a request.
   */
  webhook_config?: WebhookConfig | undefined;
  /**
   * The requested modalities of the response (TEXT, IMAGE, AUDIO).
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_modalities?: Array<ResponseModality> | undefined;
  /**
   * The mime type of the response. This is required if response_format is set.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  response_mime_type?: string | undefined;
  /**
   * The input for the interaction.
   */
  input?: InteractionsInput | undefined;
  /**
   * The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
   */
  model?: Model | undefined;
  /**
   * The agent to interact with.
   */
  agent?: AgentOption | undefined;
  /**
   * Parameters for the agent interaction.
   */
  agent_config?:
    | AntigravityAgentConfig
    | CodeMenderAgentConfig
    | DeepResearchAgentConfig
    | DynamicAgentConfig
    | undefined;
  /**
   * An audio content block.
   */
  output_audio?: AudioContent | undefined;
  /**
   * An image content block.
   */
  output_image?: ImageContent | undefined;
  /**
   * Concatenated text from the last model output in response to the current request.
   *
   * @remarks
   *
   * Note: this is added by the SDK.
   */
  output_text?: string | undefined;
  /**
   * A video content block.
   */
  output_video?: VideoContent | undefined;
};
