/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { InteractionMetadata } from "./interaction-metadata.js";

export type ListInteractionsResponse = {
  /**
   * The `InteractionMetadata` from the specified collection.
   */
  interaction_metadatas?: Array<InteractionMetadata> | undefined;
  /**
   * A token, which can be sent as `page_token` to retrieve the next page.
   *
   * @remarks
   * If this field is omitted, there are no subsequent pages.
   */
  next_page_token?: string | undefined;
};
