/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for an environment that lives on the client connection rather
 *
 * @remarks
 * than in a server-managed sandbox.
 *
 * When set (via Interaction.local_environment), the agent's filesystem and
 * shell are treated as living on the client: the agent's built-in environment
 * operations (e.g. reading/listing/editing files and running commands) are
 * suspended on the server and yielded back to the client to execute, with their
 * results returned on a subsequent turn. This is mutually exclusive with a
 * server-managed `EnvironmentConfig` (remote_environment), since the
 * environment is either on the client or in a server sandbox, never both.
 *
 * This governs only the agent's built-in environment. Client-declared function
 * tools are always executed on the client regardless of this field.
 */
export type LocalEnvironmentConfig = {
  type: "local";
};
