/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The model that will complete your prompt.\n\nSee [models](https://ai.google.dev/gemini-api/docs/models) for additional details.
 */
export type Model =
  | "gemma-4-26b-a4b-it"
  | "gemma-4-31b-it"
  | "gemini-flash-latest"
  | "gemini-flash-lite-latest"
  | "gemini-pro-latest"
  | "gemini-3.5-flash-lite"
  | "gemini-2.5-flash-image"
  | "gemini-3-flash-preview"
  | "gemini-3.1-pro-preview"
  | "gemini-3.1-pro-preview-customtools"
  | "gemini-3.1-flash-lite"
  | "gemini-3.1-flash-lite-image"
  | "gemini-3-pro-image"
  | "nano-banana-pro-preview"
  | "gemini-3.1-flash-image"
  | "gemini-nano-banana-2.1"
  | "gemini-3.1-flash-tts-preview"
  | "gemini-3.5-flash"
  | "gemini-3.6-flash"
  | "gemini-3.7-flash"
  | "gemini-3.8-flash"
  | "gemini-3.8-flash-tts"
  | "gemini-3.8-flash-lite-tts"
  | "lyria-3-clip-preview"
  | "lyria-3-pro-preview"
  | "gemini-robotics-er-2-preview"
  | "lyria-3.5"
  | "gemini-omni-1.1-flash"
  | "gemini-omni-flash-preview"
  | (string & {});
