/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Content } from "./content.js";

/**
 * The error result of the operation in case of failure or cancellation.
 */
export type ModelOutputStepError = {
  /**
   * The status code, which should be an enum value of google.rpc.Code.
   */
  code?: number | undefined;
  /**
   * A developer-facing error message, which should be in English. Any
   *
   * @remarks
   * user-facing error message should be localized and sent in the
   * google.rpc.Status.details field, or localized by the client.
   */
  message?: string | undefined;
  /**
   * A list of messages that carry the error details.  There is a common set of
   *
   * @remarks
   * message types for APIs to use.
   */
  details?: Array<{ [k: string]: any }> | undefined;
};

/**
 * Output generated by the model.
 */
export type ModelOutputStep = {
  type: "model_output";
  content?: Array<Content> | undefined;
  /**
   * The error result of the operation in case of failure or cancellation.
   */
  error?: ModelOutputStepError | undefined;
};
