/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * A server-initiated processing step for media analysis (e.g. video
 *
 * @remarks
 * understanding).
 */
export type ProcessingCallStep = {
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "processing_call";
};
