/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Config for Rank Service.
 */
export type Ranking = {
  /**
   * Optional. The model name of the rank service.
   */
  model_name?: string | undefined;
  ranking_config: "rank_service";
};
