/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The type of file retrieval to enable.
 */
export type RetrievalType =
  | "vertex_ai_search"
  | "rag_store"
  | "exa_ai_search"
  | "parallel_ai_search"
  | (string & {});
