/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { VertexAISearchConfig } from "./vertex-ai-search-config.js";

export type RetrievalType = "vertex_ai_search";

/**
 * A tool that can be used by the model to retrieve files.
 */
export type Retrieval = {
  /**
   * The types of file retrieval to enable.
   */
  retrieval_types?: Array<RetrievalType> | undefined;
  type: "retrieval";
  /**
   * Used to specify configuration for VertexAISearch.
   */
  vertex_ai_search_config?: VertexAISearchConfig | undefined;
};
