/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Required. The type of harm category to be blocked.
 */
export type SafetySettingType =
  | "hate_speech"
  | "dangerous_content"
  | "harassment"
  | "sexually_explicit"
  | "civic_integrity"
  | "image_hate"
  | "image_dangerous_content"
  | "image_harassment"
  | "image_sexually_explicit"
  | "jailbreak"
  | (string & {});

/**
 * Required. The threshold for blocking content. If the harm probability
 *
 * @remarks
 * exceeds this threshold, the content will be blocked.
 */
export type Threshold =
  | "block_low_and_above"
  | "block_medium_and_above"
  | "block_only_high"
  | "block_none"
  | "off"
  | (string & {});

/**
 * Optional. The method for blocking content. If not specified, the default
 *
 * @remarks
 * behavior is to use the probability score.
 */
export type Method = "severity" | "probability" | (string & {});

/**
 * A safety setting that affects the safety-blocking behavior.
 *
 * @remarks
 *
 * A SafetySetting consists of a
 * harm category and a
 * threshold for that
 * category.
 */
export type SafetySetting = {
  /**
   * Required. The type of harm category to be blocked.
   */
  type: SafetySettingType;
  /**
   * Required. The threshold for blocking content. If the harm probability
   *
   * @remarks
   * exceeds this threshold, the content will be blocked.
   */
  threshold: Threshold;
  /**
   * Optional. The method for blocking content. If not specified, the default
   *
   * @remarks
   * behavior is to use the probability score.
   */
  method?: Method | undefined;
};
