/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The pipeline mode of a CodeMender session. It can only be used for a
 *
 * @remarks
 * find session.
 */
export type PipelineMode = "scan" | "verify" | (string & {});

/**
 * The configuration of CodeMender sessions.
 */
export type SessionConfig = {
  /**
   * The pipeline mode of a CodeMender session. It can only be used for a
   *
   * @remarks
   * find session.
   */
  pipeline_mode?: PipelineMode | undefined;
  /**
   * The cognitive architecture or "thinking" topology used by the agent
   *
   * @remarks
   * (e.g. "default", "deep").
   */
  topology?: string | undefined;
  /**
   * The maximum number of interaction rounds the agent is allowed to perform
   *
   * @remarks
   * before reaching a timeout.
   */
  max_rounds?: number | undefined;
};
