/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The configuration of CodeMender sessions.
 */
export type SessionConfig = {
  /**
   * The maximum number of interaction rounds the agent is allowed to perform
   *
   * @remarks
   * before reaching a timeout.
   */
  max_rounds?: number | undefined;
};
