/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SpeechConfig } from "./speech-config.js";

/**
 * Optional speech mode. `VERBATIM` is default. `CONVERSATIONAL` is only
 *
 * @remarks
 * supported for multi-speaker.
 */
export type SpeakerConfigMode = "verbatim" | "conversational" | (string & {});

/**
 * Configuration for multi-speaker and speech generation.
 */
export type SpeakerConfig = {
  /**
   * Optional speech mode. `VERBATIM` is default. `CONVERSATIONAL` is only
   *
   * @remarks
   * supported for multi-speaker.
   */
  mode?: SpeakerConfigMode | undefined;
  /**
   * Individual speaker configurations.
   */
  speakers?: Array<SpeechConfig> | undefined;
};
