/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Speech annotation for text content.
 */
export type SpeechAnnotation = {
  /**
   * End of the attributed segment, exclusive.
   */
  end_index?: number | undefined;
  /**
   * The speaker to associate with this turn.
   */
  speaker?: string | undefined;
  /**
   * Start of segment of the response that is attributed to this source.
   *
   * @remarks
   *
   * Index indicates the start of the segment, measured in bytes.
   */
  start_index?: number | undefined;
  /**
   * Style instruction for the speech synthesis.
   */
  style?: string | undefined;
  type: "speech_metadata";
};
