/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Step } from "./step.js";
import { StreamMetadata } from "./stream-metadata.js";

export type StepStart = {
  /**
   * The event_id token to be used to resume the interaction stream, from
   *
   * @remarks
   * this event.
   */
  event_id?: string | undefined;
  event_type: "step.start";
  index: number;
  metadata?: StreamMetadata | undefined;
  /**
   * A step in the interaction.
   */
  step: Step;
};
