/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Annotation } from "./annotation.js";

/**
 * A text content block.
 */
export type TextContent = {
  /**
   * Citation information for model-generated content.
   */
  annotations?: Array<Annotation> | undefined;
  /**
   * Required. The text content.
   */
  text: string;
  type: "text";
};
