/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Annotation } from "./annotation.js";

export type TextAnnotationDelta = {
  /**
   * Citation information for model-generated content.
   */
  annotations?: Array<Annotation> | undefined;
  type: "text_annotation_delta";
};
