/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ThoughtSummaryContent } from "./thought-summary-content.js";

export type ThoughtSummaryDelta = {
  content?: ThoughtSummaryContent | undefined;
  type: "thought_summary";
};
