/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * The execution mode of the tool search.
 */
export type Execution = "server" | "client" | (string & {});

/**
 * A tool that allows the model to dynamically search for and load tools into
 *
 * @remarks
 * the model’s context on demand. This allows clients to avoid loading all tool
 * definitions up front and may help reduce overall token usage and cost.
 */
export type ToolSearch = {
  /**
   * A description of the function. To be set only for client-side execution.
   */
  description?: string | undefined;
  /**
   * The execution mode of the tool search.
   */
  execution?: Execution | undefined;
  /**
   * The name of the function. To be set only for client-side execution.
   */
  name?: string | undefined;
  /**
   * The JSON Schema for the function's parameters. To be set only for
   *
   * @remarks
   * client-side execution.
   */
  parameters?: any | undefined;
  type: "tool_search";
};
