/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ToolSearchCallStepArguments } from "./tool-search-call-step-arguments.js";

export type ToolSearchCallDelta = {
  arguments?: ToolSearchCallStepArguments | undefined;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "tool_search_call";
};
