/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configuration for speech recognition (transcription).
 */
export type TranscriptionConfig = {
  /**
   * Optional. A list of phrases to bias the ASR model towards.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  adaptation_phrases?: Array<string> | undefined;
  /**
   * Optional. A list of custom vocabulary phrases to bias the speech recognition model
   *
   * @remarks
   * toward recognizing specific terms.
   */
  custom_vocabulary?: Array<string> | undefined;
  /**
   * Optional. Configures speaker diarization. Supported values: "speaker".
   */
  diarization_mode?: string | undefined;
  /**
   * Optional. BCP-47 language codes providing hints about the languages present in the
   *
   * @remarks
   * audio. If omitted or empty, defaults to automatic language detection.
   */
  language_codes?: Array<string> | undefined;
  /**
   * Optional. The granularity of timestamps to include in the transcription output.
   *
   * @remarks
   * Supported values: "word". If empty, no timestamps are generated.
   */
  timestamp_granularities?: Array<string> | undefined;
};
