/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SmartTranscriptionMode } from "./smart-transcription-mode.js";
import { VerbatimTranscriptionMode } from "./verbatim-transcription-mode.js";

/**
 * Configuration for transcription mode.
 */
export type TranscriptionMode =
  | SmartTranscriptionMode
  | VerbatimTranscriptionMode;
