/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Configures transcription mode. Supported values: `VERBATIM`, `SMART`. If
 *
 * @remarks
 * unspecified, defaults to `VERBATIM` transcription. Mutually exclusive with
 * `timestamp_granularities` and `diarization_mode`.
 */
export type TranscriptionMode = "verbatim" | "smart" | (string & {});
