/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Execute a script inside the agent's container environment.
 */
export type Script = {
  /**
   * Arguments to pass to the command (e.g., [".agents/triggers/handler.js"]).
   */
  args?: Array<string> | undefined;
  /**
   * Required. Command to execute in the container (e.g., "node", "python3", "bash").
   */
  command: string;
};
