/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Arguments } from "./arguments.js";

/**
 * URL context call step.
 */
export type URLContextCallStep = {
  /**
   * The arguments to pass to the URL context.
   */
  arguments: Arguments;
  /**
   * Required. A unique ID for this specific tool call.
   */
  id: string;
  /**
   * A signature hash for backend validation.
   */
  signature?: string | undefined;
  type: "url_context_call";
};
