/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Content } from "./content.js";

export type UserInputStepContent = Array<Content> | string;

/**
 * Input provided by the user.
 */
export type UserInputStep = {
  content?: Array<Content> | string | undefined;
  type: "user_input";
};
