/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { FilterRule } from "./filter-rule.js";

/**
 * Optional declarative filter rules evaluated before waking the container.
 */
export type WebhookTriggerConfigFilter = {
  rules?: Array<FilterRule> | undefined;
};

/**
 * Signature verification configuration.
 */
export type Verification = {
  /**
   * Resource ID referencing a stored credential for signature verification.
   *
   * @remarks
   * Format: "credentials/{credential_id}"
   */
  credential_id?: string | undefined;
  /**
   * Custom header name override for non-preset HMAC verification.
   *
   * @remarks
   * Only used when preset is empty (custom verification).
   */
  custom_header_name?: string | undefined;
  /**
   * Named verification preset. Currently supported: "github".
   *
   * @remarks
   * When set, the preset configures the header name, algorithm, and
   * deduplication logic automatically.
   */
  preset?: string | undefined;
};

/**
 * Webhook-specific trigger configuration.
 */
export type WebhookTriggerConfig = {
  /**
   * Output only. Public endpoint URL for receiving webhook POST requests.
   *
   * @remarks
   * Format:
   * https://generativelanguage.googleapis.com/v1beta/agents/{agent_id}/triggers/{trigger_id}
   */
  endpoint_url?: string | undefined;
  /**
   * Optional declarative filter rules evaluated before waking the container.
   */
  filter?: WebhookTriggerConfigFilter | undefined;
  /**
   * Signature verification configuration.
   */
  verification?: Verification | undefined;
};
