/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { GoogleGenAICore } from "../core.js";
import { encodeFormQuery, encodeSimple } from "../lib/encodings.js";
import { matchStatusCode } from "../lib/http.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { GoogleGenAiError } from "../models/errors/google-gen-ai-error.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/http-client-errors.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Start an environment file upload
 *
 * @remarks
 * Starts a resumable upload session for a file in an environment workspace.
 * Upload the file bytes to the URL returned in the `X-Goog-Upload-URL`
 * response header, using the resumable upload protocol.
 */
export function environmentsInternalStartUpload(
  client: GoogleGenAICore,
  environment: string,
  path: string,
  x_goog_upload_command: "start" | undefined,
  x_goog_upload_header_content_length: number,
  x_goog_upload_header_content_type: string,
  x_goog_upload_protocol: "resumable" | undefined,
  api_version?: string | undefined,
  extract?: boolean | undefined,
  overwrite?: boolean | undefined,
  options?: Omit<RequestOptions, "extra_body">,
): APIPromise<
  Result<
    operations.StartEnvironmentFileUploadResponse | undefined,
    | GoogleGenAiError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
  >
> {
  return new APIPromise($do(
    client,
    environment,
    path,
    x_goog_upload_command,
    x_goog_upload_header_content_length,
    x_goog_upload_header_content_type,
    x_goog_upload_protocol,
    api_version,
    extract,
    overwrite,
    options,
  ));
}

async function $do(
  client: GoogleGenAICore,
  environment: string,
  path: string,
  x_goog_upload_command: "start" | undefined,
  x_goog_upload_header_content_length: number,
  x_goog_upload_header_content_type: string,
  x_goog_upload_protocol: "resumable" | undefined,
  api_version?: string | undefined,
  extract?: boolean | undefined,
  overwrite?: boolean | undefined,
  options?: Omit<RequestOptions, "extra_body">,
): Promise<
  [
    Result<
      operations.StartEnvironmentFileUploadResponse | undefined,
      | GoogleGenAiError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
    >,
    APICall,
  ]
> {
  const input: operations.StartEnvironmentFileUploadRequest = {
    environment: environment,
    path: path,
    "X-Goog-Upload-Command": x_goog_upload_command,
    "X-Goog-Upload-Header-Content-Length": x_goog_upload_header_content_length,
    "X-Goog-Upload-Header-Content-Type": x_goog_upload_header_content_type,
    "X-Goog-Upload-Protocol": x_goog_upload_protocol,
    api_version: api_version,
    extract: extract,
    overwrite: overwrite,
  };

  const payload = input;
  const body = null;

  const pathParams = {
    api_version: encodeSimple(
      "api_version",
      payload.api_version ?? client._options.api_version,
      { explode: false, charEncoding: "percent" },
    ),
    environment: encodeSimple("environment", payload.environment, {
      explode: false,
      charEncoding: "percent",
    }),
    path: encodeSimple("path", payload.path, {
      explode: false,
      charEncoding: "percentExceptReserved",
    }),
  };
  const path$ = pathToFunc(
    "/upload/{api_version}/environments/{environment}/files/{path}",
  )(pathParams);

  const query = encodeFormQuery({
    "extract": payload.extract,
    "overwrite": payload.overwrite,
  });

  const headers = new Headers(compactMap({
    Accept: "*/*",
    "X-Goog-Upload-Command": encodeSimple(
      "X-Goog-Upload-Command",
      payload["X-Goog-Upload-Command"],
      { explode: false, charEncoding: "none" },
    ),
    "X-Goog-Upload-Header-Content-Length": encodeSimple(
      "X-Goog-Upload-Header-Content-Length",
      payload["X-Goog-Upload-Header-Content-Length"],
      { explode: false, charEncoding: "none" },
    ),
    "X-Goog-Upload-Header-Content-Type": encodeSimple(
      "X-Goog-Upload-Header-Content-Type",
      payload["X-Goog-Upload-Header-Content-Type"],
      { explode: false, charEncoding: "none" },
    ),
    "X-Goog-Upload-Protocol": encodeSimple(
      "X-Goog-Upload-Protocol",
      payload["X-Goog-Upload-Protocol"],
      { explode: false, charEncoding: "none" },
    ),
  }));

  const securityInput = await extractSecurity(client._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    base_url: options?.server_url ?? client._baseURL ?? "",
    operation_id: "StartEnvironmentFileUpload",
    o_auth2_scopes: null,

    resolved_security: requestSecurity,

    security_source: client._options.security,
    retry_config: options?.retries
      || client._options.retry_config
      || {
        strategy: "attempt-count-backoff",
        backoff: {
          initialInterval: 500,
          maxInterval: 8000,
          exponent: 2,
          maxElapsedTime: 30000,
        },
        retryConnectionErrors: true,
        maxRetries: 4,
      }
      || { strategy: "none" },
    retry_codes: options?.retry_codes || ["408", "409", "429", "5XX"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "PUT",
    baseURL: options?.server_url,
    path: path$,
    headers: headers,
    query: query,
    body: body,
    userAgent: client._options.user_agent,
    timeout_ms: options?.timeout_ms || client._options.timeout_ms || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    isErrorStatusCode: (statusCode: number) =>
      matchStatusCode({ status: statusCode } as Response, ["4XX", "5XX"]),
    retryConfig: context.retry_config,
    retryCodes: context.retry_codes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    httpMeta: { response: response, request: req },
  };

  const [result] = await M.match<
    operations.StartEnvironmentFileUploadResponse | undefined,
    | GoogleGenAiError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
  >(
    M.nil<operations.StartEnvironmentFileUploadResponse | undefined>(200, {
      hdrs: true,
    }),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
