package_group(
    name = "unified_genai_visibility_group",
    packages = [
        "//ads/spam/botnets/interlab/experiment_manager/web/...",
        "//alkali/apps/adshealth/client/...",
        "//alkali/apps/makersuite/client/app/...",
        "//alkali/apps/playhub/client/...",
        "//alkali/apps/slmdebugger/client/...",
        "//alkali/apps/talosrobotviewerapp/client/...",
        "//alkali/apps/trustnexus/client/...",  # go/trustnexus
        "//analysis/magiceye/visualization/magic_bird/home/...",  # go/magiceye
        "//calendar/genai/testli_dashboard/...",
        "//caribou/ai_experiments/client/...",
        "//chrome/enterprise/productivity/ai_labs/extension/...",
        "//chrome/knowledge/retail_ai/...",
        "//chrome/privacy_sandbox/potassium/oganesson/extension/...",  #privacy-summarizer
        "//cloud/console/web/...",
        "//cloud/growth/smartsuggestions/plgcampaignsportal/query_builder/...",
        "//cloud/ml/discoveryengine/dolphin/promptpilot/web/...",
        "//cloud/security/gtig/inteldelivery/analysts/eliasfox/sauce/...",
        "//corp/collaboration/workbooklm/...",
        "//corp/gtech/ads/solutions/agenticplatform/portal/...",  # gta-agenticplatform-eng@google.com
        "//corp/gtech/ads/solutions/ginx/chrome_extension/...",
        "//corp/gtech/ads/solutions/selly/chrome_extension/...",
        "//corp/gtech/platforms/realtime_translation/...",
        "//engage/ui/sales/crm/liveassist/...",  # go/live-assist
        "//enterprise/support/cloud/bsirhns/...",
        "//experimental/chatgrowth/...",
        "//experimental/users/evgenyy/streamline/...",
        "//experimental/users/yangfanl/verifi-finals/...",  # VeriFi (b/545269610)
        "//finance_org/rmc/project_janus/frontend/...",  # fintechops-eng
        "//firebase/apptesting/web/...",  # go/firebase-app-testing
        "//fonts/fe/playground/...",  # go/fonts-team
        "//gdm/agents/activedata/ui/...",
        "//gdm/agents/sima/demo/ui/...",
        "//geo/gestalt/playground/javascript/...",  # go/earthengine
        "//google/cloud/aiplatform/sdk/genai/...",
        "//googledata/translate/twsfe/js/element/...",
        "//hardware/data/subaoi/ml_infra/...",
        "//java/com/google/cloud/security/pse/tools/gravity/...",
        "//java/com/google/corp/enterpriseplatform/agents/...",  # enterprise-platform-agents-eng@
        "//java/com/google/gdm/showcase/console/ui/...",
        "//java/com/google/geo/gt/calypso/...",  # go/calypso
        "//java/com/google/labs/aipex/zonda/boq/web/chatui/chat_app/my_info/...",
        "//java/com/google/photos/curation/webtool/server/projects/...",
        "//java/com/google/photos/theta/prototypes/...",
        "//java/com/google/research/kernel/languagelearning/webapp/sharedlanguagelearningweb/...",  # ll-core@google.com
        "//javatests/com/google/analysis/magiceye/visualization/boq/fe/ui/ai_integration_testing/...",  # go/magiceye
        "//javatests/com/google/analytics/gafe4/web/webdriverts/...",
        "//labs/aipex/scribe/web/...",
        "//labs/ix/agentplatform/browseruse/...",
        "//labs/language/genai/codelab/typescript/...",
        "//labs/language/genai/interactions/openapi/scripts/api_ref/code_samples/...",
        "//labs/language/vertical/inflow/ui/...",
        "//learning/brain/research/magenta/prompt_dj_library/...",
        "//learning/data/datagen/dataminer/...",
        "//learning/gemini/...",
        "//lens/neuralens/cadence/...",  # go/cadence-ai
        "//ops/gen/analytics/poc/genpulse/...",
        "//pipeline/crowd_compute/plugins/...",  # go/crowd-compute
        "//privacy/governance/launch_assistant/...",
        "//privacy/understanding/wickie/...",
        "//production/tools/bugai/...",
        "//research/air/frameworks/extensions/...",
        "//research/socialgood/adcanvas/...",
        "//research/xeno/web/...",
        "//sales/gcs/innovationlab/frontend/...",
        "//security/prodsec/review_request_addon/...",
        "//shopping/sai/agent/ui/projects/voice_agent/...",
        "//supplychain/hw/aardvark/...",  # dss-app-eng@
        "//third_party/a2ui_composer/shell:__pkg__",
        "//third_party/javascript/google_adk/...",
        "//third_party/javascript/google_genai/...",
        "//third_party/javascript/node_modules/vertexai/...",
        "//video/youtube/devtools/llm/tester/...",  # go/llmat-lr-device
        "//video/youtube/discovery/responsibility/...",
        "//video/youtube/partner/seed/...",
        "//video/youtube/testing/ytlr_cert/...",  # go/yts-cli
        "//video/youtube/tvfilm/unplugged/ops/...",  # go/vod-in-app-checks-automation
        "//video/youtube/web/contrib/prototypes/...",
        "//video/youtube/web/desktop/end2end/...",
        "//wireless/android/pixel/health/aurelius/...",  # go/aurelius-servers
    ],
)
