/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

export type CreateEnvironmentRequestNetworkEnum = "disabled";

/**
 * Network configuration for the environment.
 */
export type CreateEnvironmentRequestNetworkUnion =
  | interactions.EnvironmentNetworkEgressAllowlist
  | CreateEnvironmentRequestNetworkEnum;

/**
 * Request for `CreateEnvironment`.
 */
export type CreateEnvironmentRequest = {
  /**
   * Network configuration for the environment.
   */
  network?:
    | interactions.EnvironmentNetworkEgressAllowlist
    | CreateEnvironmentRequestNetworkEnum
    | undefined;
  /**
   * Sources to be mounted into the environment.
   */
  sources?: Array<interactions.Source> | undefined;
};
