/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 *
 * g3-prettier-ignore-file
 */

/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as interactions from "../interactions/index.js";

export type NetworkEnum = "disabled";

/**
 * Network configuration for the environment.
 */
export type Network =
  | interactions.EnvironmentNetworkEgressAllowlist
  | NetworkEnum;

/**
 * Output only. The status of the environment container.
 */
export type Status = "active" | "expired" | (string & {});

/**
 * An execution environment for an agent.
 */
export type Environment = {
  /**
   * Output only. The time at which the environment was created in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  created?: string | undefined;
  /**
   * Output only. The number of files in the environment, output only.
   */
  file_count?: string | undefined;
  /**
   * Required. Output only. The ID of the environment.
   */
  id: string;
  /**
   * Output only. The time at which the environment was last accessed in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  last_accessed?: string | undefined;
  /**
   * Network configuration for the environment.
   */
  network?:
    | interactions.EnvironmentNetworkEgressAllowlist
    | NetworkEnum
    | undefined;
  /**
   * Output only. The total size of the environment files in bytes, output only.
   */
  size_bytes?: string | undefined;
  /**
   * Sources to be mounted into the environment.
   */
  sources?: Array<interactions.Source> | undefined;
  /**
   * Output only. The status of the environment container.
   */
  status?: Status | undefined;
  /**
   * Output only. The time at which the environment was last updated in ISO 8601 format
   *
   * @remarks
   * (YYYY-MM-DDThh:mm:ssZ).
   */
  updated?: string | undefined;
};

/**
 * An execution environment for an agent.
 */
export type EnvironmentInput = {
  /**
   * Network configuration for the environment.
   */
  network?:
    | interactions.EnvironmentNetworkEgressAllowlist
    | NetworkEnum
    | undefined;
  /**
   * Sources to be mounted into the environment.
   */
  sources?: Array<interactions.Source> | undefined;
};
